keptn/keptn.github.io

- content/docs/0.2.0/installation/setup-keptn/index.md
In some cases, the keptn namespace remains stuck in the 'Terminating' status after executing ./uninstallKeptn.sh. Added instructions in the setup docs to solve that problem.
> added instructions to enforce deletion of keptn namespace

- content/docs/0.1.0/setup/kubernetes/install-keptn-v.0.1-eks/index.md
- content/docs/0.1.0/setup/kubernetes/install-keptn-v.0.1-gke/index.md
- content/docs/0.1.1/setup/kubernetes/install-keptn-v.0.1-eks/index.md
- content/docs/0.1.1/setup/kubernetes/install-keptn-v.0.1-gke/index.md
- content/docs/0.1.2/setup/kubernetes/install-keptn-v.0.1-eks/index.md
- content/docs/0.1.2/setup/kubernetes/install-keptn-v.0.1-gke/index.md
- content/docs/0.1.3/setup/kubernetes/install-keptn-v.0.1-eks/index.md
- content/docs/0.1.3/setup/kubernetes/install-keptn-v.0.1-gke/index.md
- content/docs/0.2.0/monitoring/dynatrace/index.md
Fix a few documentation typos from `exits` to `exists`
> Fix "exits" typos

- content/docs/0.2.0/installation/setup-keptn-gke/index.md
- The Knative build pods were still listed in the verification steps which is obsolete
- Channels that are not created were listed in the verification step
Addressing keptn/keptn#290
> Fixed verfication in install documentation

- content/docs/0.2.0/reference/keptnslog/index.md
Remove the unique ID to make it clear that users must use the KEPTN_CONTEXT from _their_ data.
> Update Elastic match query

- content/docs/develop/monitoring/dynatrace/index.md
Due to the new dynatrace-service, the configuration of Jenkins for sending Dynatrace events is not needed anymore.
> #268 Removed instructions to configure Jenkins for DT monitoring

- content/docs/0.2.1/installation/setup-keptn-gke/index.md
Since Adam figured out that python is needed on a Ubuntu 19.04, it is listed as prerequisite but annotated with a note.
> Add note '(required for Ubuntu 19.04) ' to python

- content/docs/0.2.0/monitoring/prometheus/index.md
- content/docs/0.2.0/usecases/onboard-carts-service/index.md
- content/docs/0.2.1/monitoring/prometheus/index.md
- content/docs/0.2.1/usecases/onboard-carts-service/index.md
- content/docs/develop/monitoring/prometheus/index.md
- content/docs/develop/usecases/onboard-carts-service/index.md
Instead of cloning master, it is necessary to clone a tag (branch).
> Use git clone --branch instead of cloning master

- content/docs/develop/installation/setup-keptn-gke/index.md
- content/docs/develop/reference/custom-service/index.md
- content/docs/develop/reference/keptnslog/index.md
This PR ensures a consistent use of the word artifact instead of artefact across all keptn repositories.
> #387 Fixed typo: Changed artefact to artifact

- content/docs/develop/monitoring/dynatrace/index.md
Scripts to deploy DT have been moved. Thus, it is necessary to adjust the instructions accordingly.
> Adjusting DT instructions due to move of scripts

- content/docs/0.2.1/installation/setup-keptn-gke/index.md
- content/docs/0.2.2/installation/setup-keptn-gke/index.md
- content/docs/develop/installation/setup-keptn-gke/index.md
This PR updates the installation instructions. The result of the command `kubectl get channels -n keptn` showed a wrong list of channels because keptn 0.2.0, 0.2.1 and 0.2.2 don`t deploy start-* channels.
> #415 Removed start-* channels

- content/docs/0.2.2/installation/upgrade-keptn-gke/index.md
- content/docs/0.2.2/monitoring/dynatrace/index.md
- content/docs/develop/reference/cli/index.md
When upgrading keptn from 0.2.x to 0.2.2, it is necessary to update dynatrace secret.
> Added instructions to upgrade Dynatrace secret

- .gitignore
- content/about/index.md
- content/get-in-touch/index.md
Right now the information about how to get in touch is hidden within the About section and within the keptn/community repo.
I believe making this information more prominent can help to get more people on board of the project.
I've also edited the slack invite link (similar to https://github.com/keptn/community/commit/7f96d1fe26c7d17176e78234352e6a149ee58b5d ).
Also, I've added .idea/ and .vscode/ to .gitignore.
> More information about community meetings

- content/docs/0.5.0/installation/setup-keptn/index.md
on the website we called it both Elastic Container Service as well as Elastic Kubernetes Service.
it is now changed to Elastic Kubernetes Service
> fix EKS to be called Elastic Kubernetes Service

- content/docs/develop/usecases/deployments-with-quality-gates/index.md
Dynatrace SLI Service is being released in version 0.1.0, therefore we need to checkout branch release-0.1.0 within the tutorial.
> #1059 change branch name of dynatrace-sli-service release

- content/docs/0.5.0/usecases/custom-service/index.md
- content/docs/0.6.0/usecases/custom-service/index.md
In the custom service tutorial we named our contianer "helm-service" although it was the jmeter service.
We also pointed to 0.5.0 version of the service when we should already point to 0.6.0.beta2
> Fix docs for custom service tutorial

- content/docs/0.6.0/installation/setup-keptn/index.md
- content/docs/0.6.0/usecases/onboard-carts-service/index.md
- increased EKS cluster size to to have 8 vCPUs available
- set mongo version to a fixed version instead of fetching latest
> fix Eks cluster size & mongo version

- content/docs/0.5.0/installation/setup-keptn/index.md
- content/docs/quickstart/_index.md
- content/docs/quickstart/setup_platform/setup_eks/index.md
- content/docs/quickstart/setup_platform/setup_gke/index.md
- content/home/kubernetes-cluster-top.md
As an alternative to #412, I've updated Kubernetes versions and VM sizes for quickstart and 0.5.x
> Update kubernetes versions and cluster sizes

- content/docs/0.6.0/installation/upgrade-keptn/index.md
Focus was to provide a list of breaking changes (which kind of resulted in an upgrade guide) from 0.6.0.beta2 to 0.6.0 final.
I've also added information that we have several breaking changes from 0.5.x to 0.6.0, which make it impossible to provide an upgrade script.
> #1250 Added upgrade notes for Keptn 0.6

- content/docs/0.6.0/installation/setup-keptn/index.md
- OpenShift 3.11 works (just quality gates standalone does not work)
- added instructions for Minikube 1.2
> Add instructions for minikube 1.2, re-add openshift support

- content/docs/0.5.0/concepts/architecture/index.md
- content/docs/0.5.0/reference/keptnsbridge/index.md
- content/docs/0.5.0/usecases/deployments-with-quality-gates/index.md
- content/docs/0.5.0/usecases/onboard-carts-service/index.md
- content/docs/0.5.0/usecases/self-healing-with-keptn/index.md
- content/docs/0.6.0/concepts/architecture/index.md
- content/docs/0.6.0/reference/keptnsbridge/index.md
- content/docs/0.6.0/usecases/deployments-with-quality-gates/index.md
- content/docs/0.6.0/usecases/onboard-carts-service/index.md
- content/docs/0.6.0/usecases/self-healing-with-keptn/dynatrace-scaling/index.md
- content/docs/0.6.0/usecases/self-healing-with-keptn/prometheus-scaling/index.md
I've fixed the writing of *Keptn's Bridge* for 0.6.0 and 0.5.0.
> Make sure Keptn's Bridge is always written with a capital B and K

- content/docs/0.6.0/installation/upgrade-keptn/index.md
Due to fast feedback from the community, the upgrade path for 0.6.1 should be placed on top of the page. This PR changes the order of the upgrade instructions:
> Moved upgrade instructions for 0.6.1 to the top

- content/docs/quickstart/_index.md
- content/docs/quickstart/setup_platform/setup_eks/index.md
- content/docs/quickstart/setup_platform/setup_gke/index.md
- content/docs/quickstart/setup_platform/setup_minikube/index.md
- content/docs/quickstart/setup_platform/setup_openshift/index.md
- content/docs/quickstart/setup_platform/setup_pks/index.md
Minikube 1.2 support was missing in the quickstart section.
> Provide instructions for Minikube support in Quickstart

- content/docs/0.6.0/manage/project/index.md
- content/docs/0.6.0/reference/cli/index.md
- content/docs/0.6.0/reference/helm/index.md
- content/docs/0.6.0/reference/troubleshooting/index.md
- Added information about installer failures
- re-ordered the troubleshooting section
- Added information about new-artifacts that can't be started due to insufficient cpu/memory
- Added information on how we use helm
- Added cleanup information about helm releases when executign `keptn delete project`
Preview Troubleshooting section: https://deploy-preview-476--keptn.netlify.com/docs/0.6.0/reference/troubleshooting/
Preview Helm section: https://deploy-preview-476--keptn.netlify.com/docs/0.6.0/reference/helm/
> #450 Improve trouble shooting guide

- content/docs/0.6.0/reference/managed_istio/index.md
- content/docs/develop/reference/managed_istio/index.md
This PR describes the experimental flag `--ingress-install-option` in the `keptn install` command of the CLI.
> #1712 Docu for the ingress-install-option in the install command

- content/docs/0.6.0/installation/upgrade-keptn/index.md
- content/docs/develop/operate/upgrade/index.md
Fixes https://github.com/keptn/keptn/issues/1785
> Keptn#1785 Make sure kubectl commands for ugprader are always executed in default namespace

- content/docs/0.6.0/installation/setup-keptn/index.md
- content/docs/develop/operate/install/index.md
This PR slightly simplifies the minikube installation options, by defaulting to `--gateway=NodePort`.
This means that `minikube tunnel` is optional.
> Simplified minikube installation instructions using gateway=NodePort

- content/docs/develop/operate/install/index.md
- content/docs/develop/quickstart/index.md
This PR adds K3s to the installation instructions for the current develop branch.
I also simplified the quickstart guide to avoid unnecessary redundancy. Quickstart now focuses on GKE and K3s as the primary options.
Preview quickstart: https://deploy-preview-559--keptn.netlify.app/docs/develop/quickstart/
Preview Install: https://deploy-preview-559--keptn.netlify.app/docs/develop/operate/install/
> Added K3s to installation instructions

- content/docs/0.6.0/reference/manifest_installation/index.md
- content/docs/develop/operate/manifest_installation/index.md
To make it clear that the Keptn images are built and stored on DockerHub, I added the link to the DockerHub repo for each Keptn image.
> Added link to DockerHub for keptn images

- content/docs/0.6.0/reference/manifest_installation/index.md
In this PR I have updated the experimental manifest installation with various types for 0.6.2.
If this gets accepted, I can also merge the changes into the develop folder, though with KEP 18 this might be a different story anyway.
Preview: https://deploy-preview-570--keptn.netlify.app/docs/0.6.0/reference/manifest_installation/
> Update manifest installation to support various types

- content/docs/develop/monitoring/dynatrace/install/index.md
This PR shows the new way of installing the Dynatrace Keptn integration, since it does not automatically roll-out the oneagent anymore.
> Update of docu for Dynatrace Keptn integration

- content/docs/0.7.x/troubleshooting/index.md
- content/docs/0.8.x/troubleshooting/index.md
Preview 0.7.x: https://deploy-preview-670--keptn.netlify.app/docs/0.7.x/troubleshooting/#fully-qualified-domain-names-cannot-be-reached-from-within-the-cluster
Preview 0.8.x: https://deploy-preview-670--keptn.netlify.app/docs/0.8.x/troubleshooting/#fully-qualified-domain-names-cannot-be-reached-from-within-the-cluster
> #664 Added troubleshooting guide for FQDN problems

- content/docs/0.7.x/troubleshooting/index.md
- content/docs/0.8.x/troubleshooting/index.md
Since Keptn 0.7.x we have switched to a helm based installation method, therefore we don't have an installer anymore, and we don't need to provide troubleshooting details for it.
> Removed outdated information regarding installer

- content/docs/0.8.x/continuous_delivery/deployment_helm/index.md
- content/docs/0.8.x/manage/service/index.md
With this PR I am updating the docs according to the following two issues
* https://github.com/keptn/keptn/issues/2989
* https://github.com/keptn/keptn/issues/2990
The main changes here are the fact that onboard service now works a little different (in the background), and that we have added '--all-stages` to the `keptn add-resource` command.
Previews:
* https://deploy-preview-752--keptn.netlify.app/docs/0.8.x/continuous_delivery/deployment_helm/
* https://deploy-preview-752--keptn.netlify.app/docs/0.8.x/manage/service/
> #2990 #2989 Keptn Onboard Service updates

- content/docs/0.8.x/operate/install/index.md
During setup of 0.8.0-dev I noticed that the istio ingress for api-gateway-nginx is not working anymore with istio 1.8.
As Istio 1.8+ is our current istio target version, I've updated it here accordingly.
> Update istio ingress for api-service

- content/docs/0.7.x/continuous_delivery/expose_services/index.md
- content/docs/0.7.x/troubleshooting/index.md
- content/docs/0.8.x/continuous_delivery/expose_services/index.md
- content/docs/0.8.x/troubleshooting/index.md
While going through the setup of helm-service, I noticed that we are still referring to xip.io, which is highly unreliable and causes problems.
This PR replaces occurrences of xip.io with nip.io (for 0.7.x and 0.8.x).
> Replace xip.io with nip.io

- content/docs/0.8.x/integrations/custom_integration/index.md
Related to https://github.com/keptn/keptn/issues/3418
While the distributor itself was updated to other URLs, we did not update docs accordingly. This PR fixes it.
> Fix distributor URLs for running in execution plane

- content/docs/0.6.0/reference/cli/_index.md
- content/docs/0.7.x/operate/upgrade/index.md
- content/docs/0.7.x/reference/cli/_index.md
- content/docs/0.8.x/operate/upgrade/index.md
- content/docs/0.8.x/reference/cli/_index.md
This PR updates instructions when downloading the CLI via get.keptn.sh.
* we don't use `sudo -E bash` anymore, `bash` is enough
* old versions of Keptn can still be downloaded, but `KEPTN_VERSION=x.y.z` needs to be specified
> Update get.keptn.sh quickstart instructions

- content/community/kubecon-eu-2021/index.md
Adding a landing page for KubeCon 2021 so we can provide some additional information around the event.
> adding kubecon page

- config.toml
As outlined in #794 the 404 pages have broken CSS.
Hugo is assuming the 404 page will appear under `/404/index.html`. But as the web server is not redirecting to 404 but just rewriting the request these paths are being messed up.
Switching off relative linking should not only resolve this issue but also avoid links like
```
<link rel="stylesheet" href="../../../../../../js/libs/doc/lightbox/css/lightbox.min.min.1bbb47ec548f1c47e276ce27971cdc27f8c803ee4bb96f064c72c7448f7c0f12.css">
```
> Disable relative URLs. fixes #794

- content/docs/0.8.x/continuous_delivery/deployment_helm/index.md
- content/docs/0.8.x/manage/service/index.md
docs for keptn/keptn#3585
Preview: https://deploy-preview-807--keptn.netlify.app/docs/0.8.x/manage/service/
> keptn/keptn#3585 Describe service naming rule

- content/docs/0.8.x/automated_operations/remediation/index.md
- content/docs/0.8.x/continuous_delivery/multi_stage/index.md
- content/docs/0.8.x/manage/project/index.md
- content/docs/0.8.x/manage/shipyard/index.md
- content/docs/0.8.x/quality_gates/get_started/index.md
As part of https://github.com/keptn/examples/issues/166 I took the chance and restructured our docs regarding Shipyard file.
1. I believe that there was too much information hidden in the *Continuous delivery* section, hence I have moved it out to the *Manage Keptn*/*Shipyard* section.
**Preview**: https://deploy-preview-815--keptn.netlify.app/docs/0.8.x/manage/shipyard/
2. I have also added an example of adding a `remediation` sequence to the *Update shipyard* docs (Preview: https://deploy-preview-815--keptn.netlify.app/docs/0.8.x/manage/shipyard/#add-remove-a-task-sequence-to-from-a-stage scroll down to Use Case 2)
3. Multi-stage continuous-delivery has been extended by multiple examples. Preview: https://deploy-preview-815--keptn.netlify.app/docs/0.8.x/continuous_delivery/multi_stage/ …
> Restructure docs regarding shipyard file

- content/docs/0.8.x/operate/api_token/index.md
The selector of the api-service has changed from `run=api-service` to `app.kubernetes.io/name: api-service`, see https://github.com/keptn/keptn/blob/master/installer/manifests/keptn/charts/control-plane/templates/core.yaml#L52
> Correct the selector of the api-service

- layouts/partials/announcement.html
I believe it would be a good idea to keep the announcements on keptn.sh instead of linking to github
> keeping the announcment on keptn.sh

- content/docs/0.8.x/integrations/custom_integration/index.md
This PR describes how Keptn Integrations can use the new `sh.keptn.log.error` events to inform Keptn about errors
> Describe logging feature of Keptn distributor

- content/docs/quickstart/get-demo.sh
Signed-off-by: DarthBenro008 <hkpdev008@gmail.com>
As mentioned in #843 , a quick addition to check for helm installation before proceeding with demo installation of quick-start instructions
> add: helm installation check for quickstart demo

- content/docs/0.8.x/operate/advanced_install_options/index.md
Part of https://github.com/keptn/keptn/issues/4183
As discussed, this will remove the air-gapped instructions for now.
As I believe that the link might already be communicated to end-users, I have left the heading in place. This allows people to access the link (e.g., https://keptn.sh/docs/0.8.x/operate/advanced_install_options/#example-execute-helm-upgrade-without-internet-connectivity ) and get some information.
**PREVIEW**: https://deploy-preview-849--keptn.netlify.app/docs/0.8.x/operate/advanced_install_options/#example-execute-helm-upgrade-without-internet-connectivity
> keptn/keptn#4183 Remove airgapped installation instructions

- content/docs/0.8.x/monitoring/dynatrace/install/index.md
Signed-off-by: Arthur Pitman <arthur.pitman@dynatrace.com>
This PR updates the documentation to describe installing the *dynatrace-service* with optional Keptn credentials in the `dynatrace` secret, released in dynatrace-service 0.15.0.
For more information about these changes in the *dynatrace-service*, see https://github.com/keptn-contrib/dynatrace-service/issues/309
> Describe optional Keptn credentials in DT secret

- .github/workflows/auto-update.yml
**This PR**
* adds a workflow to automatically update the keptn CLI docs when a new keptn/keptn version (tag) is pushed
* creates a PR against this repo to update the docs which can then be reviewed and accepted
Signed-off-by: Moritz Wiesinger <moritz.wiesinger@dynatrace.com>
> ci: Add workflow to auto generate docs on receiving release-push event (#2927)

- .github/workflows/auto-update.yml
**This PR**
* fixes a small bug where GH actions can't pick up the env variable that is set dynamically in the pipeline
Signed-off-by: Moritz Wiesinger <moritz.wiesinger@dynatrace.com>
> fix: Fix bug where env variable can not be correctly picked up by GH actions (#2927)

- .github/actions/spelling/patterns.txt
- content/docs/0.8.x/operate/advanced_install_options/index.md
Part of https://github.com/keptn/keptn/issues/4183
**Note**: It is impossible to ensure that this works with Keptn 0.8.4 for two reasons:
1. We cannot configure the image `alpine:3.13` which is used as an initContainer in configuration-service to be loaded from another registry.
2. We cannot specify a registry that is on a non-default port (e.g., 5000)
For both issues we have implemented a fix in Keptn that has already been merged to master branch, so it should be included in the next release.
However, this means: **DO NOT MERGE THIS PR UNTIL THE NEXT KEPTN RELEASE IS READY**
**Verifying instructions**
Create a cluster with a separate registry using `k3d`:
```
k3d registry create myregistry.localhost --port 50005 …
```
> Update installation instructions for airgapped installation

- content/docs/quickstart/_index.md
- content/docs/quickstart/exposeKeptnConfigureIstio.sh
To mitigate issues with `istioctl` and M1 chips, let us switch to the Helm install version for Istio.
> use Helm to install Istio

- content/docs/0.10.x/operate/advanced_install_options/index.md
This PR ensures that the correct script for the airgapped installation is used.
Related:
https://github.com/keptn/keptn/pull/5532
> Use the correct script for airgapped installation for 0.10.x

- content/docs/0.11.x/manage/shipyard/index.md
> chore: Added note about fallback to manual approval strategy

- content/docs/quickstart/_index.md
Just refactoris the introduction a bit and provides guidelines how to get help
> Minor updates for the Keptn tutorial

- content/docs/0.11.x/continuous_delivery/delivery_assistant/index.md
- content/docs/0.11.x/continuous_delivery/deployment_helm/index.md
- content/docs/0.11.x/continuous_delivery/multi_stage/index.md
- content/docs/0.11.x/manage/service/index.md
Due to a new release of the [carts service](https://github.com/keptn-sockshop/carts/releases/tag/0.13.0), an update of the docs for the newest Keptn version had to be done. 
> docs: Change from carts:0.11 to carts:0.13 for Keptn 0.11.x

- CONTRIBUTING.md
- README.md
- content/community/contributing/index.md
This change initializes contributor guidelines for non-code contributions:
* Documentation
* Advocacy and Outreach
* Mentorship programs and internships
* Recommendations for monetary donations that we do not accept at the moment (right?)
* Placeholder for other types of contributions, e.g. design
Contributes to https://github.com/keptn/community/issues/82 . Also fixes #862 by moving the contributing content to a separate page.
> Contributor Guide: Document non-code contributions

- layouts/partials/intro.html
Until https://github.com/keptn/community/issues/89 is ready, we cannot serve the public demo.
Tutorials are also updated by https://github.com/keptn/tutorials/pull/216
> Disable the public demo

- content/docs/0.10.x/automated_operations/remediation/index.md
- content/docs/0.10.x/continuous_delivery/multi_stage/index.md
- content/docs/0.10.x/integrations/how_integrate/index.md
- content/docs/0.10.x/manage/project/index.md
- content/docs/0.10.x/manage/shipyard/index.md
- content/docs/0.10.x/quality_gates/get_started/index.md
- content/docs/0.11.x/automated_operations/remediation/index.md
- content/docs/0.11.x/continuous_delivery/multi_stage/index.md
- content/docs/0.11.x/integrations/how_integrate/index.md
- content/docs/0.11.x/manage/project/index.md
- content/docs/0.11.x/manage/shipyard/index.md
- content/docs/0.11.x/quality_gates/get_started/index.md
- content/docs/0.12.x/automated_operations/remediation/index.md
- content/docs/0.12.x/continuous_delivery/multi_stage/index.md
- content/docs/0.12.x/integrations/how_integrate/index.md
- content/docs/0.12.x/manage/project/index.md
- content/docs/0.12.x/manage/shipyard/index.md
- content/docs/0.12.x/quality_gates/get_started/index.md
Since Keptn 0.10, the spec.keptn.sh version of Shipyard is: `spec.keptn.sh/0.2.3` (see: https://github.com/keptn/keptn/releases/tag/0.10.0). Consequently, I updated it to be correct.
> Update of shipyard spec to: `spec.keptn.sh/0.2.3` for 0.10, 0.11, 0.12

- content/docs/0.10.x/operate/advanced_install_options/index.md
- content/docs/0.10.x/operate/upgrade/index.md
- content/docs/0.11.x/operate/advanced_install_options/index.md
- content/docs/0.11.x/operate/upgrade/index.md
- content/docs/0.12.x/operate/advanced_install_options/index.md
- content/docs/0.12.x/operate/upgrade/index.md
- content/docs/0.7.x/operate/advanced_install_options/index.md
- content/docs/0.7.x/operate/upgrade/index.md
- content/docs/0.8.x/operate/advanced_install_options/index.md
- content/docs/0.8.x/operate/upgrade/index.md
- content/docs/0.9.x/operate/advanced_install_options/index.md
- content/docs/0.9.x/operate/upgrade/index.md
- content/docs/concepts/architecture/index.md
- content/docs/quickstart/_index.md
- changes all URLs pointing to the keptn helm charts to point to the new charts repository https://charts.keptn.sh
- fixes a sentence on the architecture page
> docs: Update helm chart URL to point to new chart repository

- layouts/partials/footer.html
Signed-off-by: Juergen Etzlstorfer <jetzlstorfer@microsoft.com>
Removes the link to my outdated calendly. can be seen as a temporary fix until a new calendly link can be provided.
fixes #1014
> fix: remove link to calendly

- content/docs/0.10.x/monitoring/dynatrace/install/index.md
- content/docs/0.11.x/monitoring/dynatrace/install/index.md
- content/docs/0.12.x/monitoring/dynatrace/install/index.md
According to https://github.com/keptn-contrib/dynatrace-service/blob/master/documentation/project-setup.md#create-a-secret-with-keptn-cli, creating a new secret for dynatrace-service requires a scope="dynatrace-service" flag since dynatrace-service 0.18.
I've adapted this for Keptn 0.10, 0.11 and 0.12:
* for 0.10, I made it optional with a note to add it for newer versions of dynatrace-service [Preview 0.10](https://deploy-preview-1022--keptn.netlify.app/docs/0.10.x/monitoring/dynatrace/install/#2-create-a-secret-with-credentials)
* for 0.11, I made it the default, leaving a note that older versions don't need this [Preview 0.11](https://deploy-preview-1022--keptn.netlify.app/docs/0.11.x/monitoring/dynatrace/install/#2-create-a-secret-with-credentials)
* for 0.12, I made it required to …
> fix: dynatrace-service requires scoped secrets since 0.18

- content/docs/0.12.x/operate/upgrade/index.md
Upgrade instructions for Keptn 0.12 referred to 0.12.x, which should have been 0.11.x.
> Fix: upgrade instructions for Keptn 0.12 referred to 0.12

- content/docs/0.10.x/_index.md
- content/docs/0.9.x/_index.md
This PR hides the release documentation for `0.9.x` and `0.10.x` from the menu. The content is still available and accessible via a link to `https://keptn.sh/docs/0.9.x/` and `https://keptn.sh/docs/0.10.x/`
> Hide Release 0.9.x and 0.10.x in the docs

- content/docs/integrations/_index.md
Currently filtering is done by using the `ts_query_web`, which filters using a full text search. I just asked the Artifacthub team if it's also possible to filter by annotations like `keptn/kind` or `keptn/version`. If this is possible I'll update the code appropriately.
Preview: https://deploy-preview-1075--keptn.netlify.app/docs/integrations/
Fixes #1036
> feat: Added Webhook filter to integrations page

- assets/js/libs/doc/misc.js
- content/docs/0.10.x/reference/cli/_index.md
- content/docs/0.11.x/reference/cli/_index.md
- content/docs/0.12.x/reference/cli/_index.md
- content/docs/0.13.x/reference/cli/_index.md
- content/docs/0.14.x/reference/cli/_index.md
- content/docs/0.7.x/reference/cli/_index.md
- content/docs/0.8.x/reference/cli/_index.md
- content/docs/0.9.x/reference/cli/_index.md
- content/docs/quickstart/_index.md
- data/principles.json
MacOS should be macOS
`macOS` is a proprietary graphical operating system developed and marketed by Apple Inc. since 2001. It is the primary operating system for Apple's Mac computers. [Wikipedia](https://en.wikipedia.org/wiki/MacOS)
> Fix:fix a typo and refactored MACOS to macOs

- content/docs/0.13.x/operate/backup_and_restore/index.md
Fixed the correct use of Back up (verb) and Backup (adjective) in the file `Backup_and_restore` Markdown page
> Fixed "backup" vs "back up" in Backup & Restore page

- content/docs/quickstart/_index.md
Rewrote intro to Quick Start.  Am pushing this alone so it can be reconciled with what Meha Bhalodiya is doing.
@agardnerIT convinced me that the Quick Start should just show the Helm chart and Docker options  and we put all of the manual installation instructions into the Install docs but I will do that in a separate PR.  I want to compare what is in Quick Start with what is currently in the Install docs and be sure that we end up with the best information when we're done.  For now, just imagine that material gone from the Quick Start.
> Rewrote intro to Quick Start

- content/docs/0.11.x/monitoring/dynatrace/install/index.md
- content/docs/0.12.x/monitoring/dynatrace/install/index.md
- content/docs/0.13.x/monitoring/dynatrace/install/index.md
This PR fixes the bullet points of the **Notes** section of page `monitoring/dynatrace/install` for versions `0.11.x`, `0.12.x` and `0.13.x`
> fix: bullet points for install page of monitoring/dynatrace corrected

- content/docs/0.11.x/monitoring/dynatrace/troubleshooting/index.md
- content/docs/0.12.x/monitoring/dynatrace/troubleshooting/index.md
- content/docs/0.13.x/monitoring/dynatrace/troubleshooting/index.md
- content/docs/0.14.x/monitoring/dynatrace/troubleshooting/index.md
This PR adds a single section to `monitoring/dynatrace` for versions `0.11.x`, `0.12.x`, `0.13.x` and `0.14.x` with a link to the troubleshooting guide at [dynatrace-service](https://github.com/keptn-contrib/dynatrace-service)
> feat: add troubleshooting guide for monitoring dynatrace

- content/docs/0.11.x/monitoring/dynatrace/install/index.md
- content/docs/0.12.x/monitoring/dynatrace/install/index.md
- content/docs/0.13.x/monitoring/dynatrace/install/index.md
- content/docs/0.14.x/monitoring/dynatrace/install/index.md
This PR
* adds the same fix for version `0.14.x` as #1156 added for `0.11.x`, `0.12.x` and `0.13.x`
* fixes VERSION hint for **dynatrace-service** in versions `0.11.x`, `0.12.x`, `0.13.x` and `0.14.x`
* adds missing `--scope="dynatrace-service"` of `keptn create secret` command for versions `0.13.x` and `0.14.x`
* fixes link to **dynatrace-service** compatibility matrix in versions `0.11.x`, `0.12.x`, `0.13.x` and `0.14.x`
> fix: monitoring dynatrace install pages

- content/docs/concepts/architecture/index.md
- content/docs/concepts/automated_operations/index.md
- content/docs/concepts/delivery/index.md
- content/docs/concepts/quality_gates/index.md
- content/docs/concepts/secrets/index.md
This PR fixes xrefs from Concepts articles so they reference the release 0.14.x docs rather than 0.8.x
Also fixed one little syntactical error at the end of the "Secret Service" article.
> Update xrefs in "Concepts" articles

- content/docs/0.14.x/operate/upgrade/index.md
Changed the `helm upgrade` command to use `--values` flag instead of `--reuse-values`.
> Update of helm upgrade command in Keptn 0.14. upgrade guide

- content/docs/concepts/_index.md
- content/docs/quickstart/_index.md
- content/docs/roadmap/_index.md
- content/docs/tutorials/_index.md
The Quick Start, Concepts, Roadmap, and Tutorials sections had weights of 1, 2, 3, and 4 so no way to interpolate other sections between them.  This changes those weights to 10, 20, 30, and 40 to allow for some expansion.
> Modified weights for top-level sections

- content/docs/0.14.x/monitoring/prometheus/_index.md
- content/docs/0.14.x/monitoring/prometheus/install/index.md
- content/docs/0.15.x/monitoring/prometheus/_index.md
- content/docs/0.15.x/monitoring/prometheus/install/index.md
Clarifies doc about where prometheus-server must be installed and the use of another external prometheus-server, based on https://keptn.slack.com/archives/CNRCGFU3U/p1651033964668509 .
Also fixed a couple syntactical errors in the files.
This PR contains identical changes for the 0.15.x and 0.14.x trees.
> Clarify installation of "local" and external prometheus-service

- content/docs/0.14.x/operate/advanced_install_options/index.md
Fix a small typo on the 0.14.1 advanced install page. A hyperlink mentioned v0.13 when it should be called `0.14.1`
Ironically there's a typo in the branch name: `type` should be `typo` :)
Signed-off-by: adamgardnerit <adam@agardner.net>
> fix typo from 13 to 14

- content/docs/0.13.x/monitoring/prometheus/install/index.md
- content/docs/0.14.x/monitoring/prometheus/_index.md
- content/docs/0.14.x/monitoring/prometheus/install/index.md
- content/docs/0.15.x/monitoring/prometheus/_index.md
- content/docs/0.15.x/monitoring/prometheus/install/index.md
This PR simplifies the installation instructions for prometheus-service, based on the latest releases which use a helm Chart.
> docs: Update prometheus installation instructions for Keptn 0.13, 0.14 and 0.15

- content/docs/0.15.x/manage/git_upstream/index.md
This also needs to be added to 0.16.x when possible.
https://github.com/keptn/keptn.github.io/issues/1230
> Add caveat about self-signed certificates for upstream Git repo

- content/docs/concepts/architecture/index.md
- content/docs/concepts/automated_operations/index.md
- content/docs/concepts/delivery/index.md
- content/docs/concepts/quality_gates/index.md
Fixes some xrefs from "Concepts" articles.  Mostly, xrefs that had 0.14.x hard-coded but a couple that should point to new reference pages and the Bridge section rather than Bridge pages that were under reference.
> Fix xrefs for 0.15.x

- content/docs/0.16.x/manage/shipyard/index.md
- content/docs/0.16.x/manage/triggers/index.md
- content/docs/0.16.x/reference/files/shipyard/index.md
This PR does the following:
* Creates a reference page for the shipyard.yaml file to summarize the synopsis of the file.  We will certainly refine this page more and add xrefs to this file from other pages as we move forward but, if reviewers agree, this is the general shape of the page.
* Deletes old material from the manage/shipyard file that is now in this file.
* Creates a separate manage/triggers file.  Note that this is unchanged from what was previously in the manage/shipyard file so does not require review for this exercise.
Issues for review:
* Should this page be called "shipyard.yaml" or just "shipyard"?
* Are the elements in this file "fields" or "parameters" or something else?
* What should be included in the …
> add shipyard ref, manage triggers, modify manage shipyard

- content/docs/0.16.x/reference/files/_index.md
- content/docs/0.16.x/reference/files/sli/index.md
- content/docs/0.16.x/reference/files/slo/index.md
* Renamed Files section to Configuration section per discussion
* Renamed sli.yaml and slo.yaml to be sli and slo
That PR has one comment, questioning whether this section should be "Configuration Files" rather than just "Configurations".
I believe the consensus from the Developer Meeting was to just use "Configuration" but it is certainly open to discussion.
This replaces https://github.com/keptn/keptn.github.io/pull/1249 , which had contents that should have been in two PRs.
> Configuration section rather than files

- content/docs/0.16.x/_index.md
This updates the weight for the 0.16.x tree so it is displayed before the 0.15.x tree
> make 0.16.x show before 0.15.x

- content/docs/0.17.x/_index.md
- public/google90258e79df368ea0.html
Modified weight for 0.17.x
This picked up the fact that I had to delete my public directory to clean up the html checking locally.  That directory should probably be in the .gitignore file, right?
> Make 0.17.x show before 0.16.x

- static/google90258e79df368ea0.html
Within  #1275 we accidentally deleted our google site verification file (i am not sure if we still need it) - due to the fact, that it was just put into the `public` folder which contains the generated sources.
As this is a static file, it should have been placed wihtin `static` which will generate the same result, but `public` will be just an `output` directory, which can be fully ignored.
> Moving static file to correct folder

- content/docs/explore/index.md
- content/docs/quickstart/_index.md
- updates the quickstart page with latest changes to the helm installation process according to Keptn 0.17
> docs: Update quickstart page for Keptn 0.17

- content/docs/0.16.x/reference/files/shipyard/index.md
- content/docs/0.17.x/reference/files/shipyard/index.md
https://keptn.slack.com/archives/CNRCGFU3U/p1656682769397519 points out that we do not specify rules for naming stages.  This PR solves that problem
@johannes-b @thisthat @mowies
> Add rules for naming shipyard stages

- content/docs/0.12.x/integrations/webhooks/_index.md
- content/docs/0.13.x/integrations/webhooks/_index.md
- content/docs/0.14.x/integrations/webhooks/_index.md
- content/docs/0.15.x/integrations/webhooks/_index.md
- content/docs/0.16.x/integrations/webhooks/_index.md
- content/docs/0.17.x/integrations/webhooks/_index.md
During reading the docs I found that there was a syntax error in using go-templating in webhooks.
This PR corrects the syntax error, and also slightly adapts the text (e.g., it's not about string characters, it's about alphanumeric characters. `@` is also a string, but it's not alphanumeric).
> fix: correct webhook-service go templating

- config.toml
- adds a baseURL to our hugo config
- This should solve the problem that the [sitemap for keptn.sh](https://keptn.sh/sitemap.xml) doesn't have full URLs inside, which is needed for SEO purposes
> Fix sitemap base URL

- content/docs/0.18.x/integrations/how_integrate/index.md
This PR:
- Removes references to the generic executor service as it is deprecated and unsupported.
- Favours the job executor service
> Remove deprecated and unsupported generic executor service

- content/docs/0.18.x/api/git_provisioning/index.md
This PR:
- Adds a section for available Git provisioners to the correct page
- Adds Gitea as an available provisioner
- Adds text and links for new integrations
> Add Gitea provisioner

- content/home/usage.md
Fixes build problems I introduced when I used a YouTube iframe rather than the Hugo shortcode.
@StackScribe @thisthat requesting a priority review and merge so doc site can be rebuilt again.
> youtube fix: use shortcode

- content/docs/install/multi-cluster/index.md
This PR:
- Updates links of the multi-cluster page to 0.18.1
- Adds a note stating that normally execution integrations are containers deployed on a remote k8s cluster but they don't necessarily need to be. You could poll the Keptn API and so have non-containerised workloads executing Keptn tasks.
> Fix old links and add point about non-k8s execution plane integrations

- content/docs/concepts/keptn-tools/index.md
Closes #1349 
This PR:
- Adds a new section at the end of the "Keptn tools" page linking to the explore keptn docs
This will help guide potential users to try out Keptn.
> Keptn tools page: Add try keptn link and fix xref from 0.17.x to 0.18.x

- content/docs/explore/index.md
This PR:
- Fixes some naming issues (`kilrcoda` should be `Killercoda`)
- Fixes links point to an old release on the explore page (from `0.16.x` to `0.18.x`)
> explore Keptn fix links point to 0.16.x

- content/docs/integrations/_index.md
This PR:
- Slightly alters the wording on the `docs/integrations` page to funnel people to the keptn/integrations repo
- It also adds links to Slack for those stuck
> Update contributing integrations wording

- layouts/partials/tools-cards.html
This PR:
- Adds  `alt` and `title` attributes to homepage integrations
- Changes "add tool" links to point to `https://github.com/keptn/integrations` as the funnel for new tooling integrations
Helps with SEO, accessibility and usability. Now when a user hovers over a logo, they see the name of the integration. I no longer need to know what logo I'm looking at
> Usability / SEO: Add image alt and title tags

- .htmltest.yml
- layouts/partials/footer.html
fixes #1344
1. I removed the `Docs` & `Tutorials` Parts from Resources.
2. Added `s` to `integration`
3. Added `Explore Keptn` which takes us to the link: https://keptn.sh/docs/explore/
Signed-off-by: Omkar kulkarni [88308267+Omkar0114@users.noreply.github.com](mailto:88308267+Omkar0114@users.noreply.github.com)
> Updated footer.html

- content/community/_index.md
Signed-off-by: Bishal Das <bishalhnj127@gmail.com>
Typo `amd` fixed by this PR
> Typo `amd` is fixed

- content/docs/0.17.x/api/git_provisioning/index.md
- content/docs/0.18.x/api/git_provisioning/index.md
- content/docs/0.19.x/api/git_provisioning/index.md
- For 0.18 the `control-plane.features.automaticProvisioningURL` Helm value was changed to `features.automaticProvisioning.serviceURL`.
Signed-off-by: TannerGilbert <gilberttanner.work@gmail.com>
> fix: Fixed broken link to automatic provisioning Helm value

- content/docs/0.13.x/_index.md
- content/docs/0.14.x/_index.md
- content/docs/0.15.x/_index.md
With a release date in May, version 0.15 and older when out of the 3-months window to not officially display it in the keptn/docs anymore. 
Signed-off-by: Johannes Bräuer <johannes.braeuer@gmx.at>
> Hide version 0.13, 0.14, and 0.15

- content/docs/0.18.x/reference/miscellaneous/distributor/index.md
- content/docs/install/multi-cluster/index.md
This is an alternative presentation to https://github.com/keptn/keptn.github.io/pull/1382 , which fixes https://github.com/keptn/keptn/issues/8576 .  It makes adjusting the exec plane name a step in the process of implementing a multi-cluster environment rather than an afterthought.
The original draft had the following issues.  Giovanni responded and I believe these are fixed:
* I made up the examples without much knowledge -- please suggest better examples
* The text says that this is so the distributor can handle event subscriptions correctly, then says that the nameOverride value is available only if the integration uses the distributor.  This does not sound right.
* What happens if someone sets different values for …
> Alternate presentation of multi-cluster exec plane names

- content/docs/0.18.x/reference/files/shipyard/index.md
- content/docs/0.19.x/reference/files/shipyard/index.md
@grabnerandi provided technical detail about the implicit `evaluation` sequence that is provided in every stage.  Preserving that info in the shipyard reference file.
Applied to both 0.18.x and 0.19.x
> Explain implicit evaluation sequence in shipyard ref

- content/docs/0.12.x/_index.md
- content/docs/0.13.x/_index.md
- content/docs/0.14.x/_index.md
- content/docs/0.15.x/_index.md
- content/docs/0.16.x/_index.md
- content/docs/0.17.x/_index.md
- content/docs/0.19.x/_index.md
Provide a banner that shows:
* 0.12, 0.13, 0.14, 0.15 are not supported, and
* 0.19 is under development. 
Signed-off-by: Johannes Bräuer <johannes.braeuer@gmx.at>
>  Marked 0.12, 0.13, 0.14, and 0.15 as unsupported and 0.19 under development

- content/docs/0.18.x/reference/miscellaneous/distributor/index.md
- content/docs/0.19.x/reference/files/values/index.md
Fixes broken xrefs to helm-service and jmeter-service, which are now in keptn-contrib
> xrefs to keptn-contrib for helm-service & jmeter-service

- content/community/_index.md
- content/home/contact-left.md
This PR:
- Removes the "Ask an expert" section as the calendly link is no longer valid
- Thus fixes and closes #1392 
> remove ask an expert. fixes #1392

- content/docs/0.18.x/reference/miscellaneous/distributor/index.md
- content/docs/0.19.x/reference/files/values/index.md
- content/docs/install/_index.md
- content/docs/install/helm-install/index.md
- content/docs/install/multi-cluster/index.md
This PR replaces https://github.com/keptn/keptn.github.io/pull/1375 .  See that PR for review history.
* Add link to @agardnerIT 's video of a simple installation
* Update and sync docs with video. Two goals:
* Ensure that the video and doc do not contradict each other. Docs have far more info than video and that is fine, just do not want contradictions
* Ensure that all commands used in the video are in the docs for easy copy/paste
* 
Additional work is needed for these pages, including:
* Revise/rework instructions beyond Control Plane installation. I changed the header levels of these sections to correct the structure but did not revise contents.
* Improve flow between this page and multi-cluster. This includes using the …
> Add quick installation demo video and synchronize doc and video

- content/docs/0.14.x/bridge/version_check/index.md
- content/docs/0.15.x/bridge/version_check/index.md
- content/docs/0.16.x/bridge/version_check/index.md
- content/docs/0.17.x/bridge/version_check/index.md
- content/docs/0.18.x/bridge/version_check/index.md
- content/docs/0.19.x/bridge/version_check/index.md
- Fixes broken link on Keptn Bridge starting Keptn 0.14.x by adding an alias to version check documentation.
Resolves #1411
Signed-off-by: TannerGilbert <gilberttanner.work@gmail.com>
> fix: Added aliases for version check documentation starting 0.14.x

- content/docs/0.19.x/operate/statistics/index.md
This is just a quickie PR to move the "Statistics" page from "Concepts" to the "Operate" section.
* I made.a few non-consequential edits to the text
* This topic is not a priority for development at this time.  We just want to move it to a logical location.
> Move "Statistics" to "Operate" section

- content/docs/quickstart/_index.md
This PR:
- Removes an FAQ entity because it refers to the outdated `keptn install` method
> Remove outdated FAQ reference to keptn install on Quickstart page

- content/docs/0.19.x/operate/secrets/index.md
Moving existing content from "Concepts" to "Operate".  A couple minor editorial changes but basically no change to content.  This topic is not a top priority for further development at this time.
> Move "Secrets Service" from "Concepts" to "Operate"

- content/docs/0.19.x/define/delivery_sequence/index.md
- content/docs/0.19.x/define/quality-gates/index.md
- content/docs/0.19.x/manage/plan/index.md
- content/docs/0.19.x/manage/service/index.md
- content/docs/0.19.x/reference/files/shipyard/index.md
* Move the "Create service" page to "Manage" section
* Add instructions for creating a service from the Keptn Bridge.  I will link Adam's "Create project and service video" to that section after it is moved to the Keptn youtube area.  I want to get this PR merged quickly so I can reference it from other docs.
* A few minor edits
> Move service page to "Manage" section

- content/docs/0.19.x/define/_index.md
- content/docs/0.19.x/define/delivery_assistant/index.md
- content/docs/0.19.x/define/delivery_sequence/index.md
- content/docs/0.19.x/define/quality-gates/index.md
- content/docs/0.19.x/define/simple-project/index.md
- content/docs/0.19.x/define/task-sequence/index.md
- content/docs/0.19.x/define/triggers/index.md
Signed-off-by: Meg McRoberts meg.mcroberts@dynatrace.com
This PR attempts to provide a bit of structure and coherence to the "Define a project" section with the following:
* Summary/intro list on landing page to provide sort of a reference learning path
* Some adjustments to the content of each individual page
This PR does not address checking the code and information to be sure it is up-to-date for current releases
This section needs major work.  Some good info but a lot of duplication/redundancy and not a lot of depth.  Each page is really just some sample shipyards without context and a list of what is required to implement the functionality or how to run it.  We need to step back to identify what is really required and what is the best way to present it -- some combination of videos …
> Add structure/coherence to "Define" section

- content/docs/0.19.x/reference/files/sli/index.md
- content/docs/concepts/quality_gates/index.md
This preserves information @grabnerandi provided to a customer question.
I tried to genericize the info while using Dynatrace as an example -- I couldn't figure out where this is in the Prometheus configuration.  And I'm not sure what I wrote is totally accurate and clear.
We probably need an example of this but maybe we should build it into a bigger sample in the "define" guide section and just link to that here.
https://github.com/keptn/keptn.github.io/issues/1396
> How to use different SLI environments for different projects/services/stages

- content/docs/0.16.x/reference/files/shipyard/index.md
- content/docs/0.17.x/reference/files/shipyard/index.md
- content/docs/0.18.x/manage/update/index.md
- content/docs/0.18.x/reference/files/shipyard/index.md
- content/docs/0.19.x/manage/update/index.md
- content/docs/0.19.x/reference/files/shipyard/index.md
KEP-70 to allow adding/deleting/modifying stages in a shipyard after it is created is no longer active so deleting all references to it from the docs.
https://github.com/keptn/keptn.github.io/issues/1472
> Remove references to KEP-70

- content/docs/concepts/keptn-tools/index.md
- content/docs/install/authenticate-cli-bridge/index.md
- content/docs/install/cli-install/index.md
- content/docs/install/k8s/index.md
- content/docs/install/multi-cluster/index.md
Checking the xrefs broken for 1.0.x unearthed some outdated xrefs in 0.19.x docs.  Those are fixed here
https://github.com/keptn/keptn.github.io/issues/1496
> Fix outdated xrefs in 0.19.x docs

- layouts/partials/announcement.html
This PR:
- Removes the outdated kubecon announcement from top banner
> Remove kubecon announcement

- content/docs/1.0.x/concepts/architecture/index.md
- content/docs/1.0.x/install/helm-install/index.md
Updates the helm-install section to refer to 1.0.0 for all commands.
Also made the mongoDB section in architecture reference the instructions here for using an externally configured MongoDB.
Part of https://github.com/keptn/keptn.github.io/issues/1511
> Use 1.0.0 for helm-install section

- content/docs/1.0.x/define/quality-gates/index.md
This PR captures information @grabnerandi provided on slack about how to extract evaluation results and push them to an external service using either Webhooks or the Keptn API.
> Summarize how to push evaluation results to external service

- config.toml
- content/docs/1.0.x/_index.md
- content/docs/quickstart/_index.md
- content/docs/roadmap/_index.md
Replaces https://github.com/keptn/keptn.github.io/pull/1543 which has some bizarre xref test failures.
Supplements https://github.com/keptn/keptn.github.io/pull/1547 , which deprecates some older releases.
> remove quickstart, roadmap, tutorial links

- content/docs/1.0.x/bridge/version_check/index.md
- content/docs/1.0.x/define/delivery_assistant/index.md
- content/docs/1.0.x/define/delivery_sequence/index.md
- content/docs/1.0.x/define/deployment_helm/index.md
- content/docs/1.0.x/define/quality-gates/index.md
within 0.19 we added aliases for moved pages - we have forgotten to also move them to the new version. This is fixing the build for the future.
> Add aliases for moved pages

- content/docs/0.14.x/integrations/custom_integration/index.md
- content/docs/0.14.x/reference/miscellaneous/distributor/index.md
- content/docs/1.0.x/bridge/_index.md
- content/docs/1.0.x/bridge/basic_authentication/index.md
- content/docs/1.0.x/bridge/deep_linking/index.md
- content/docs/1.0.x/bridge/manage_projects/index.md
- content/docs/1.0.x/bridge/manage_sequences/index.md
- content/docs/1.0.x/bridge/manage_services/index.md
- content/docs/1.0.x/bridge/oauth/index.md
- content/docs/1.0.x/bridge/version_check/index.md
- content/docs/1.0.x/define/quality-gates/index.md
- content/docs/1.0.x/install/monitoring/index.md
- content/docs/1.0.x/install/upgrade/index.md
- content/docs/1.0.x/integrations/webhooks/_index.md
- content/docs/1.0.x/reference/files/distributor/index.md
Our htmltest only checks newer versions, but there have been missing canonical urls to our newest version. We are adding those now, so our URLs are better configured.
should tackle a lot of those issues
> Add proper aliases for missing canonical urls

- content/community/contributing/index.md
On [https://keptn.sh/community/contributing/](https://keptn.sh/community/contributing/) there's a typo at the line
"If you are **interested Most of the Keptn codebase** is implemented in Golang and JavaScript/Angular"
The above typo has been fixed to
"If you are **interested, most of the Keptn codebase** is implemented in Golang and JavaScript/Angular"
Signed-off-by: Chaitanya Bisht [chaitanya.bisht10@gmail.com](mailto:chaitanya.bisht10@gmail.com)
> Fixed typo in the Contributing Guide

- content/docs/1.0.x/install/authenticate-cli-bridge/index.md
- content/docs/1.0.x/install/cli-install/index.md
- content/docs/1.0.x/reference/cli/_index.md
This PR does the following:
* Remove install/authenticate instructions from the CLI reference section
* Merges appropriate information into the install/cli-install page
* Merges appropriate information into the install/autheticate-cli-bridge page
* Also adds links to the Bridge pages about basic authentication and oauth
This PR replaces https://github.com/keptn/keptn.github.io/pull/1562/ , which in turn replaced https://github.com/keptn/keptn.github.io/pull/1542 .
> Move CLI install/authenticate info from CLI ref to install section

- config.toml
- layouts/sitemap.xml
Our sitemap contained too many pages, also those which are refering to a more up to date version. This is/was problematic for SEO. Search engines do see the sitemap as source of truth and get confused if there are pages, which declare themselves as outdated. Hence that, we are removing all outdated versions from the sitemap.xml
> Sitemap clean up

- layouts/partials/canonical.html
Checking first if a page exists, if not, we are checking for aliases and use the proper page with the aliases.
Additionally we add some self referential links to the page.
This fixes our 333 issues with canonical URLs, which are just redirecting and therefore are suboptimal :)
> Adding a more robust logic to canonical urls

- layouts/partials/canonical.html
Our canonical urls worked perfectly locally and with our makefile, but on netlify we are using a url, and the links have been broken.
This change fixes the build for netlify but keeping it working locally.
> Fixing canonical urls for netlify

- CONTRIBUTING.md
- config.toml
- content/docs/1.0.x/api/git_provisioning/index.md
- content/docs/1.0.x/install/helm-install/index.md
- content/docs/1.0.x/install/k8s/index.md
- content/docs/1.0.x/install/upgrade/index.md
- content/docs/1.0.x/integrations/custom_integration/index.md
- content/docs/1.0.x/manage/service/index.md
- content/docs/1.0.x/manage/tasks/index.md
ONLY GIOVANNI SHOULD MERGE THIS PR!
This PR does the following:
* Update the version= field in the config.yaml file to 1.1.0
* Parameterize the release number in places where the current release. string should always be parameterized
* Updated the CONTRIBUTING.md file to explain how release version is now parameterized
This PR does NOT do the following because I think these things are not required:
* Parameterize the release number when specified to the `keyword` field in the metadata
* Modify the contents of the "Upgrade" section for 1.1.0.  The title is "Upgrade from Keptn 0.19.x to 1.0.x" and I do not think we have any breaking changes that require user action in this release.  Let me know if I'm wrong and I will write up the …
> Update to 1.1.0; parameterize release number

- config.toml
- content/404/_index.md
- layouts/partials/canonical.html
- layouts/sitemap.xml
Currently we do have version 1.1.x but our folders are still 1.0.x - we use the same variable for version within the docs and for our SEO improvements. By raising the version, and not renaming also the directory all our canonical urls broke, and even our sitemap was not fully populated. To mitigate this, I introduced another variable, called `versionDirectory` which states, where our documentation is currently sitting and adapted all the necessary snippets.
> Folder and Version difference hotfix

- content/docs/1.0.x/define/tracetest/index.md
This PR provides a bit of information about using Tracetest with documentation.
Adnan's blog post and documentation on the Integrations page are excellent so I went for short and sweet?  Would it be better if I added a little bit more, like maybe the "we make it possible" list from the blog that gives more details about Tracetest or do we figure that anyone who is curious can click and get to all the information?
Do you have a video or anything else you would like linked?
> Point to Tracetest from define section

- content/resources/user-adoption/index.md
- layouts/partials/happy-users-logos.html
This fixes the broken xref to the ADOPTERS file, which was recently moved to the community repo.  This links to the raw markdown file.  It would be better if it linked to a rendered file but this at least fixes the broken xref which is causing other PRs to fail CI.
> new location for ADOPTERS file

- content/docs/1.0.x/define/parallel/index.md
- content/docs/1.0.x/define/triggers/index.md
- content/docs/1.0.x/reference/files/shipyard/index.md
* Create "Run tasks in parallel" page in the "Define Keptn Project" section to preserve Giovanni's information about creating multiple stages that trigger off a previous stage.
* Link to this new page from the shipyard reference file that discusses parallelism
* Fixed a tiny typo in the define/triggers page because I saw it and it wasn't worth a separate PR.
Thanks to Francesco Furnari for asking the question and @thisthat for providing the answer!
> Add information about running tasks in parallel

- assets/scss/pages/_doc.scss
Signed-off-by: Nitishupkr [nitishupkr@gmail.com](mailto:nitishupkr@gmail.com)
fixes : #1640 
the text buttons which are colliding are now fixed they are not colliding and its is responsive to the all device .And a Netlify build is ready to be used so we can display the page and check the docs section of the integration
see:https://friendly-longma-79936e.netlify.app/docs/integrations/
> remove the colliding of buttton in the integration docs 

- content/docs/concepts/architecture/index.md
- content/docs/concepts/automated_operations/index.md
- content/docs/concepts/keptn-tools/index.md
- content/docs/concepts/quality_gates/index.md
Fixes #1496
- Changed `0.18.x` to `1.0.x`.
- Changed `0.19.x` to `1.0.x`
> fix: outdated links in cocepts

- layouts/partials/header.html
youtube links are failing for some reasons
> add announcement for EoL
