content/docs/0.2.0/usecases/custom-service/index.md

instructions for writing a custom service

Custom service

---

content/docs/0.2.0/installation/setup-keptn/index.md
content/docs/0.2.0/usecases/onboard-carts-service/index.md

added detailed installation verification steps
explained the responsibilities of the github service in more detail 
minor changes to the onboarding instructions

Doc refinement

---

content/docs/develop/installation/setup-keptn-gke/index.md
content/docs/develop/monitoring/dynatrace/index.md
content/docs/develop/monitoring/prometheus/index.md
content/docs/develop/usecases/deployments-with-quality-gates/index.md
content/docs/develop/usecases/onboard-carts-service/index.md
content/docs/develop/usecases/runbook-automation-and-self-healing/index.md

The sections 'Setup Dynatrace' and 'Runbook Automation and Self-healing' have be adapted to reflect the changes needed to support Dynatrace managed tenants.

#255 Update of instructions for supporting DT managed

---

content/docs/develop/usecases/runbook-automation-and-self-healing/index.md

- added comment on prerequisite of use case

Clarify prerequisites

---

content/docs/develop/reference/troubleshooting/index.md
content/docs/develop/usecases/onboard-carts-service/index.md

A new section in keptn/docs should list instructions to trouble shoot known issues. 
(+ fixed a absolute path)

#369 Proposal for a trouble shooting section

---

content/docs/develop/installation/setup-keptn-gke/index.md
content/docs/develop/usecases/onboard-carts-service/index.md

Since Adam provided changes for version 0.2.1, it is necessary to also update the contents\docs\develop folder, which is the documentation for the upcoming release.

Add edits from Adam also to the contents\docs\develop folder

---

content/docs/develop/usecases/onboard-carts-service/index.md

- Add commands so that the user can easily open Jenkins as well as the carts service

#341 Improve read experience

---

content/docs/develop/installation/setup-keptn-gke/index.md
content/docs/develop/installation/upgrade-keptn-gke/index.md
content/docs/develop/monitoring/dynatrace/index.md
content/docs/develop/monitoring/prometheus/index.md
content/docs/develop/reference/cli/index.md
content/docs/develop/reference/custom-service/index.md
content/docs/develop/reference/keptnslog/index.md
content/docs/develop/reference/troubleshooting/index.md
content/docs/develop/usecases/deployments-with-quality-gates/index.md
content/docs/develop/usecases/onboard-carts-service/index.md
content/docs/develop/usecases/runbook-automation-and-self-healing/index.md

This PR takes care of streamlining the look-and-feel with special focus on:
- Style of headlines
- Use of kubectl commands
- Image size

#341 Streamlining look-and-feel

---

content/docs/develop/reference/cli/index.md

Provide instructions to use KEPTN_PROJECT, KEPTN_STAGE, and KEPTN_SERVICE as environment variable.

#386 Added three keptn environment variables

---

content/docs/develop/reference/custom-service/index.md

This PR updates the example for logging due to question from external contributor

Update of example for logging

---

layouts/index.html

changed meta tags for social sharing

changed meta tags

---

layouts/partials/footer.html

Update slack link to include shared link

Slack Link with invite

---

content/docs/0.5.0/reference/monitoring/dynatrace/index.md
content/docs/develop/reference/monitoring/dynatrace/index.md

I added some more details on the Dynatrace Setup Instructions for GKE with Container-optimized os.
I hope it is okay that I edited those docs in 0.5.0 and develop folder.

#1000 improve dynatrace setup instructions

---

README.md
content/docs/develop/reference/monitoring/dynatrace/index.md
content/docs/develop/usecases/onboard-carts-service/index.md

- Fixed typo in README.md
- Onboarding Tutorial: No need to add performance tests to dev
- Onboarding Tutorial: No need to add functional tests to staging
- Quick explaination of what the provided shipyard file does
- Reference to shipyard spec updated to new keptn/spec repo
- Create project workflow updated such that the default option (create without git upstream) is always visible

#1014 Improved onboarding tutorial

---

content/docs/develop/usecases/self-healing-with-keptn/index.md

#1059 change spec version

---

content/docs/0.5.0/reference/monitoring/dynatrace/index.md
content/docs/0.6.0/reference/monitoring/dynatrace/index.md

Slightly reworked the "restarting pods" when using GKE with COS.

Dynatrace-Integration: Restarting pods

---

content/docs/quickstart/_index.md

- Added `kubectl` as a requirement
- Added a quick verification step using `keptn status`

Updated quickstart guide

---

content/docs/0.6.0/usecases/quality-gates/index.md

Removes the step of using the applyAutoTaggingRule.sh which caused issues

Updated version of Dynatrace Tagging

---

content/home/contact-right.md

wrong day was displayed for community meetings.

fix communitymeeting day

---

content/docs/integrations/_index.md
content/docs/quickstart/_index.md

This PR addresses the issue #393 and provides a first version of the integrations page.

#393 First version of Integrations page

---

content/docs/0.6.0/usecases/custom-service/index.md

Update tutorial for writing your own keptn service with the new servie template (keptn/#913)

Update tutorial for writing your own keptn service with the new servie template

---

content/docs/0.6.0/reference/manifest_installation/index.md

See https://github.com/keptn/keptn/pull/1754

Add install step for api gateway nginx

---

content/docs/0.6.0/installation/setup-keptn/index.md
content/docs/develop/installation/setup-keptn/index.md
content/docs/quickstart/setup_platform/setup_gke/index.md

we got a wrong partner link from google and have to update it. created a new bitly with the new partner link

fix gke link

---

content/docs/0.6.0/reference/api/index.md
content/docs/0.6.0/reference/api_token/index.md
content/docs/0.6.0/reference/manifest_installation/index.md
content/docs/develop/operate/api_token/index.md
content/docs/develop/operate/manifest_installation/index.md
content/docs/develop/operate/upgrade/index.md
content/docs/develop/reference/api/index.md
content/docs/develop/reference/cli/_index.md

Explanation of how to retrieve, create, re-create the API token. (in both, the official 0.6.2 docu and develop folder)

#549 Provide help for managing the API token

---

content/docs/0.6.0/manage/service/index.md
content/docs/develop/manage/service/index.md

Potentially fixes https://github.com/keptn/keptn/issues/1870

#1870 Add replicaCount in values

---

content/docs/0.7.x/monitoring/dynatrace/install/index.md
content/docs/0.7.x/monitoring/dynatrace/sli_provider/index.md
content/docs/0.7.x/monitoring/prometheus/install/index.md
content/docs/0.7.x/monitoring/prometheus/sli-provider/index.md
content/docs/0.8.x/monitoring/dynatrace/install/index.md
content/docs/0.8.x/monitoring/dynatrace/sli_provider/index.md
content/docs/0.8.x/monitoring/prometheus/install/index.md
content/docs/0.8.x/monitoring/prometheus/sli-provider/index.md

#641 Fixing problems with install dynatrace-service and prometheus-service

---

content/docs/0.7.x/manage/git_upstream/index.md

Addresses https://github.com/keptn/keptn/issues/2487 in the docs

Show a warning for the new default GitHub branch name

---

content/docs/0.7.x/operate/backup_and_restore/index.md

#674 fix base64 decode command

---

content/docs/0.8.x/operate/backup_and_restore/index.md

Fixes #674 (now for the 0.8 folder)

fix echo64 decode command

---

content/docs/quickstart/_index.md

This PR explains how to access the Keptn Bridge after installing Keptn.

Explain how to access Keptn Bridge in Quickstart

---

content/docs/0.7.x/monitoring/dynatrace/best_practices/index.md
content/docs/0.8.x/monitoring/dynatrace/best_practices/index.md
content/docs/quickstart/_index.md

Signed-off-by: Marc Campbell <marc.e.campbell@gmail.com>

Fix spelling of Kubernetes

---

content/docs/0.7.x/reference/bridge/_index.md

adding info on EAP

---

content/docs/0.8.x/continuous_delivery/delivery_assistant/index.md
content/docs/0.8.x/continuous_delivery/multi_stage/index.md
content/docs/0.8.x/integrations/action_provider/index.md
content/docs/0.8.x/integrations/custom_integration/index.md
content/docs/0.8.x/integrations/sli_provider/index.md
content/docs/0.8.x/manage/project/index.md
content/docs/0.8.x/quality_gates/get_started/index.md
content/docs/0.8.x/quality_gates/integration/index.md
content/docs/0.8.x/reference/cli/commands/keptn_get_event.md
content/docs/0.8.x/reference/cli/commands/keptn_send_event.md

Closes #667 
Note: I have already updated all links to the spec to refer to version 0.2.0 (which has not been released yet). we will need to check all of the links when the new version of the spec is available

#667 update shipyards and cloudevents

---

content/docs/0.7.x/operate/install/index.md
content/docs/0.8.x/operate/install/index.md
content/docs/quickstart/_index.md

streamlined quickstart instructions

Update quickstart instructions and kubernetes versiosn

---

content/home/happy-users-logos.md

update dt logo

---

LICENSE-docs
README.md
layouts/partials/footer.html

Adding copyright to footer:
- Keptn authors
- Linux foundation
fixes: https://github.com/keptn/keptn.github.io/issues/717

Adding copyright to footer as per CNCF website guidelines

---

content/home/happy-users.md
layouts/partials/footer.html

adding link & clarify text

---

content/docs/0.8.x/operate/upgrade/index.md

#2500 Instructions for upgrading from 0.7 to 0.8

---

content/docs/0.8.x/operate/install/index.md

#706 Fixed apiVersion of ingress example

---

content/docs/0.8.x/integrations/custom_integration/index.md

This PR reflects the changes made in https://github.com/keptn/keptn/issues/3001

Updated distributor proxy URLs

---

content/community/_index.md
content/community/contributing/index.md
content/community/faq/index.md
content/community/meetings/index.md
content/community/rockstars/index.md
layouts/partials/main-menu.html

adding community pages

---

content/docs/0.8.x/_index.md

improve wording for develop banner

---

content/resources/user-adoption/index.md

adding Triscon user group presentation

---

layouts/partials/happy-users.html

add missing quote character

---

layouts/partials/announcement.html

remove banner

---

content/docs/0.8.x/reference/bridge/deep_linking/index.md

Associated PR: [#3207 Deep Links](https://github.com/keptn/keptn/pull/3339)
Signed-off-by: Klaus Strießnig <k.striessnig@gmail.com>

deep-links update

---

content/docs/0.8.x/reference/cli/_index.md

Signed-off-by: Hemanth Krishna (DarthBenro008) <hkpdev008@gmail.com>
Signed-off-by: DarthBenro008 <hkpdev008@gmail.com>
Fixes #729 
superseedes PR https://github.com/keptn/keptn.github.io/pull/758
I have squashed the commits and removed the generated files

add: #729 Keptn CLI Autocompletion Instructions

---

content/docs/0.8.x/continuous_delivery/deployment_helm/index.md

Signed-off-by: warber <bernd.warmuth@dynatrace.com>
Preview: https://deploy-preview-762--keptn.netlify.app/docs/0.8.x/continuous_delivery/deployment_helm/

added documentation about user-managed deployments

---

layouts/partials/announcement.html

Removed the word patch

---

content/docs/quickstart/_index.md

Update of quickstart

---

content/docs/0.8.x/quality_gates/get_started/index.md

Changed stage name by replacing underscore with hyphen

---

content/resources/concepts/index.md

adding user group video

---

layouts/partials/announcement.html

Fixed release notes URL

---

content/community/kubecon-eu-2021/index.md

adding content

---

content/docs/0.6.0/installation/backup_and_restore/index.md
content/docs/0.7.x/operate/backup_and_restore/index.md
content/docs/0.8.x/operate/backup_and_restore/index.md

This PR will fix the following Issue:
https://github.com/keptn/keptn/issues/3754

Escape $FILE variable

---

content/docs/0.8.x/operate/install/index.md

adding istio install hint

---

content/docs/0.8.x/manage/git_upstream/index.md

Fixed typo

---

content/docs/0.8.x/operate/backup_and_restore/index.md

Added warning to make sure `kubectl` is properly connected

---

content/docs/0.8.x/monitoring/prometheus/install/index.md

Refactoring doc for the new changes in the prometheus-service
Issue- keptn-contrib/prometheus-service#53
Signed-off-by: Raj Das mail.rajdas@gmail.com

Updating prometheus doc for the new installation steps

---

layouts/partials/announcement.html

adding kubecon link

---

content/community/kubecon-eu-2021/index.md

add link to office hours

---

content/docs/0.8.x/reference/cli/_index.md

Superseedes https://github.com/keptn/keptn.github.io/pull/704
This PR introduces instructions for installing the Keptn CLI via homebrew (as requested in https://github.com/keptn/keptn/issues/2864 )

Add homebrew instructions

---

content/community/kubecon-eu-2021/index.md
content/community/newsletter/index.md

- Hiding the KubeCon landing page from the menu
- Adding newsletter archive 

adding newsletter archive

---

content/docs/0.8.x/continuous_delivery/deployment_helm/index.md

Part of https://github.com/keptn/keptn/issues/3757

#3757 How to define custom deployment URIs for user_managed deployments

---

content/resources/integrations/index.md

adding locust user group video

---

content/docs/0.8.x/automated_operations/remediation/index.md
content/docs/0.8.x/continuous_delivery/delivery_assistant/index.md
content/docs/0.8.x/continuous_delivery/multi_stage/index.md
content/docs/0.8.x/integrations/action_provider/index.md
content/docs/0.8.x/integrations/custom_integration/index.md
content/docs/0.8.x/integrations/sli_provider/index.md
content/docs/0.8.x/manage/project/index.md
content/docs/0.8.x/manage/shipyard/index.md
content/docs/0.8.x/quality_gates/get_started/index.md
content/docs/0.8.x/quality_gates/integration/index.md

Changed Shipyard of examples and links from version from 0.2.0 to 0.2.2

---

content/docs/integrations/_index.md

fix dynatrace sli version

---

netlify.toml

- Fixes #824 
Preview can be found here: https://keptndocs.benro.tech/
And logs can be found here: https://app.netlify.com/sites/hopeful-jones-ae4868/deploys/60acfbfd20db5a000787fce4
cc: @jetzlstorfer

add: hugo version in netlify.tom

---

.github/actions/spelling/expect.txt
content/docs/quickstart/.gitignore
content/docs/quickstart/_index.md
content/docs/quickstart/clean-project.sh
content/docs/quickstart/exposeKeptnConfigureIstio.sh
content/docs/quickstart/get-demo.sh
content/docs/quickstart/quickstart.sh

New quickstart guide to run Keptn locally

---

content/docs/quickstart/_index.md
content/docs/quickstart/get-demo.sh

add hardening step

---

content/docs/integrations/_index.md

Added note for prometheus-service

---

content/docs/0.8.x/operate/k8s_support/index.md

Update of resource consumption

---

content/resources/user-adoption/index.md

adding user group recording

---

content/docs/0.8.x/troubleshooting/index.md

#771 Add istio related troubleshooting step

---

content/docs/0.8.x/monitoring/dynatrace/install/index.md

Signed-off-by: Arthur Pitman <arthur.pitman@dynatrace.com>
This PR fixes the documentation for the KEPTN_API_URL and KEPTN_BRIDGE_URL values.

Fix incorrect KEPTN_API_URL and KEPTN_BRIDGE_URL

---

content/docs/quickstart/get-demo.sh

- Update to use latest Prometheus service 
- Remove Prometheus SLi service as it is now part of the Prometheus service anyway

update Prometheus integration

---

content/docs/0.8.x/_index.md
content/docs/0.8.x/continuous_delivery/deployment_helm/index.md
content/docs/0.8.x/integrations/custom_integration/index.md
content/docs/0.8.x/operate/advanced_install_options/index.md
content/docs/0.8.x/operate/install/index.md
content/docs/0.8.x/operate/multi_cluster/index.md
content/docs/0.8.x/operate/upgrade/index.md
content/docs/0.8.x/reference/bridge/_index.md
content/docs/0.8.x/reference/cli/commands/keptn.md
content/docs/news/release_announcements/keptn-085/index.md
layouts/partials/announcement.html

Update docs for 0.8.5

---

content/community/contributing/index.md

Fix the broken link in the contributor guide

---

content/docs/0.8.x/_index.md
content/docs/0.8.x/continuous_delivery/deployment_helm/index.md
content/docs/0.8.x/integrations/custom_integration/index.md
content/docs/0.8.x/operate/advanced_install_options/index.md
content/docs/0.8.x/operate/install/index.md
content/docs/0.8.x/operate/multi_cluster/index.md
content/docs/0.8.x/operate/upgrade/index.md
content/docs/0.8.x/reference/bridge/_index.md
content/docs/news/release_announcements/keptn-086/index.md
layouts/partials/announcement.html

Update to version 0.8.6

---

content/docs/concepts/assets.txt

adding link to sources

---

content/resources/integrations/index.md

adding artillery video

---

content/resources/user-adoption/index.md

adding mindtree user group

---

content/docs/0.8.x/integrations/custom_integration/index.md

add filter description

---

content/docs/0.8.x/monitoring/dynatrace/uninstall/index.md

Signed-off-by: Arthur Pitman <arthur.pitman@dynatrace.com>

Update dynatrace-service uninstall guidelines

---

README.md
content/docs/0.8.x/monitoring/dynatrace/assets/README.md
content/docs/0.8.x/monitoring/dynatrace/install/index.md

This PR removes extra whitespaces and fixes the links in README.md. 
Furthermore, it removes an empty list point from "Monitoring > Dynatrace"

Small clean-up

---

content/home/contact-left.md
layouts/partials/contact.html
layouts/partials/footer.html

adding 1on1 links

---

content/docs/0.8.x/_index.md
content/docs/0.8.x/continuous_delivery/deployment_helm/index.md
content/docs/0.8.x/integrations/custom_integration/index.md
content/docs/0.8.x/operate/advanced_install_options/index.md
content/docs/0.8.x/operate/install/index.md
content/docs/0.8.x/operate/multi_cluster/index.md
content/docs/0.8.x/operate/upgrade/index.md
content/docs/news/release_announcements/keptn-087/index.md
layouts/partials/announcement.html

Release 0.8.7

---

content/docs/news/release_announcements/keptn-087/index.md

Fix release order

---

content/docs/roadmap/_index.md
content/docs/tutorials/_index.md

This PR adds a link to the Keptn roadmap 

Add roadmap to menu

---

content/docs/0.9.x/operate/install/index.md
content/docs/0.9.x/reference/bridge/basic_authentication/index.md

Update documentation for Bridge credentials

---

config.toml

Signed-off-by: Elisabeth Lang <elisabeth.lang@dynatrace.com>

Enable docs for 0.9.0

---

content/docs/0.9.x/operate/upgrade/index.md
content/docs/news/release_announcements/keptn-090/index.md
layouts/partials/announcement.html

Add announcement Keptn 0.9.0

---

content/docs/quickstart/_index.md

docs: update quick start links

---

content/docs/news/release_announcements/keptn-091/index.md
layouts/partials/announcement.html

**DO NOT MERGE YET**
Preview: https://deploy-preview-913--keptn.netlify.app/

docs: Add release announcement of 0.9.1

---

content/docs/0.9.x/operate/upgrade/index.md
content/docs/news/release_announcements/keptn-092/index.md
layouts/partials/announcement.html

Preview: https://deploy-preview-918--keptn.netlify.app/

docs: Add release of 0.9.2

---

content/docs/0.9.x/_index.md

Fixed release version from 0.9.0 to 0.9.2

---

content/docs/0.10.x/continuous_delivery/deployment_helm/index.md
content/docs/0.10.x/continuous_delivery/multi_stage/index.md
content/docs/0.10.x/manage/service/index.md
content/docs/0.10.x/monitoring/prometheus/install/index.md
content/docs/0.10.x/reference/bridge/_index.md
content/docs/0.10.x/reference/cli/_index.md

Removed the keptn onboard command

---

content/docs/0.10.x/reference/bridge/deep_linking/index.md

Signed-off-by: Klaus Strießnig <k.striessnig@gmail.com>

docs(bridge): Removed deprecated links

---

content/docs/0.9.x/monitoring/prometheus/install/index.md

Update of Prometheus docu

---

content/docs/integrations/_index.md

Signed-off-by: TannerGilbert <gilberttanner.work@gmail.com>

Added artifacthub widget to integration page

---

content/docs/0.9.x/operate/advanced_install_options/index.md

This PR fixes the airgapped installation for 0.9.x

Fix airgapped install for 0.9.2

---

content/docs/0.9.x/operate/advanced_install_options/index.md

After the merge, an update for 0.10.0 needs to be done.

Add helm install commands

---

content/docs/0.8.x/reference/cli/commands/keptn_configure_monitoring.md
content/docs/0.8.x/reference/cli/commands/keptn_create_project.md
content/docs/0.8.x/reference/cli/commands/keptn_delete_project.md
content/docs/0.8.x/reference/cli/commands/keptn_install.md
content/docs/0.8.x/reference/cli/commands/keptn_uninstall.md
content/docs/0.8.x/reference/cli/commands/keptn_update_project.md
content/docs/0.8.x/reference/cli/commands/keptn_upgrade.md
content/docs/0.8.x/reference/cli/commands/keptn_upgrade_project.md
content/docs/0.9.x/reference/cli/commands/keptn_configure_monitoring.md
content/docs/0.9.x/reference/cli/commands/keptn_create_project.md
content/docs/0.9.x/reference/cli/commands/keptn_delete_project.md
content/docs/0.9.x/reference/cli/commands/keptn_install.md
content/docs/0.9.x/reference/cli/commands/keptn_uninstall.md
content/docs/0.9.x/reference/cli/commands/keptn_update_project.md
content/docs/0.9.x/reference/cli/commands/keptn_upgrade.md
content/docs/0.9.x/reference/cli/commands/keptn_upgrade_project.md

This PR adds the missing version number in several links

fix: Added missing version in URLs

---

content/docs/news/release_announcements/keptn-0100/index.md
layouts/partials/announcement.html

chore: Add release announcement Keptn 0.10.0

---

content/docs/0.10.x/operate/upgrade/index.md

fix: use correct version number

---

content/docs/0.10.x/manage/shipyard/index.md
content/docs/concepts/glossary/index.md

Explain term Resource in Glossary

---

content/docs/quickstart/_index.md

chore: Update quickstart

---

content/docs/0.10.x/integrations/webhooks/_index.md

Show how to leverage Go templating for Webhook Payload

---

content/docs/0.11.x/operate/upgrade/index.md
content/docs/news/release_announcements/keptn-0112/index.md

Patched upgrade process

---

content/docs/0.11.x/operate/backup_and_restore/index.md

docs: restore DB

---

content/docs/concepts/performance_validation/index.md
content/docs/concepts/quality_gates/index.md

Shaping the use-case around quality gates to emphasize release/deployment validation

---

content/docs/quickstart/_index.md

Improves look & feel of the guide, and helps to externally reference particular items

Quickstart: Add sections and hyperlink anchors

---

content/community/_index.md
content/community/meetings/index.md

Contributes to https://github.com/keptn/community/issues/71

Document community.cncf.io as a new platform for meetings

---

content/docs/0.11.x/quality_gates/integration/index.md

Provide guidance to write evaluation triggered event

---

content/docs/0.11.x/continuous_delivery/deployment_helm/index.md
content/docs/0.11.x/integrations/custom_integration/index.md
content/docs/0.11.x/operate/advanced_install_options/index.md
content/docs/0.11.x/operate/install/index.md
content/docs/0.11.x/operate/k8s_support/index.md
content/docs/0.11.x/operate/multi_cluster/index.md
content/docs/0.11.x/operate/upgrade/index.md
content/docs/news/release_announcements/keptn-0114/index.md
layouts/partials/announcement.html

Prepare release 0.11.4

---

content/docs/0.11.x/operate/upgrade/index.md

Provide hint to do Helm upgrade

---

content/docs/news/vulnerability_bulletins/keptn-sec-2020-003/index.md
content/docs/news/vulnerability_bulletins/keptn-sec-2021-001/index.md

Vulnerability bulletin for log4j via JMeter

---

content/docs/0.11.x/operate/upgrade/index.md

Help for setting context before `keptn upgrade`

---

config.toml
content/docs/news/release_announcements/keptn-0120/index.md
content/docs/quickstart/_index.md
layouts/partials/announcement.html

feat: Announce Keptn 0.12.0

---

content/docs/news/release_announcements/keptn-0120/index.md

fix: Release title

---

content/docs/0.10.x/operate/install/index.md
content/docs/0.11.x/operate/install/index.md
content/docs/0.12.x/operate/install/index.md
content/docs/0.7.x/operate/install/index.md
content/docs/0.8.x/operate/install/index.md
content/docs/0.9.x/operate/install/index.md

Signed-off-by: odubajDT <ondrej.dubaj@dynatrace.com>
Fixes https://github.com/keptn/keptn/issues/4407

docs: Updated Ingress and Istio manifests to support Openshift 3.11

---

content/docs/0.10.x/operate/api_token/index.md
content/docs/0.11.x/operate/api_token/index.md
content/docs/0.12.x/operate/api_token/index.md
content/docs/0.13.x/operate/api_token/index.md

Preview: https://deploy-preview-1020--keptn.netlify.app/docs/0.12.x/operate/api_token/

docs: Better cmd for API-Token generation

---

content/docs/0.11.x/manage/shipyard/index.md
content/docs/0.12.x/manage/shipyard/index.md
content/docs/0.13.x/manage/shipyard/index.md

Fixes #1019 
Preview: https://deploy-preview-1023--keptn.netlify.app/docs/0.12.x/manage/shipyard/#trigger-a-sequence

doc: Provide examples for triggering a sequence

---

content/docs/concepts/delivery/index.md

fix broken xref to shipyard config

---

content/docs/concepts/quality_gates/index.md

This replaces https://github.com/keptn/keptn.github.io/pull/1031 but with proper signoff.

"tod deliver" -> "to deliver" (first PR) redux

---

content/docs/0.13.x/operate/user_management/oauth_secrets/index.md

Related PR: https://github.com/keptn/keptn/pull/6689/
Signed-off-by: Klaus Strießnig <k.striessnig@gmail.com>

docs: Manage OpenID session secrets

---

content/docs/news/release_announcements/keptn-0121/index.md
layouts/partials/announcement.html

Signed-off-by: Giovanni Liva <giovanni.liva.91@gmail.com>

docs: Announce Kepnt 0.12.1

---

config.toml
content/docs/0.10.x/_index.md
content/docs/0.11.x/_index.md
content/docs/0.8.x/_index.md
layouts/partials/sidebar-multicard.html

Render 0.8 but hide in menu

---

CONTRIBUTING.md

I added some information about things that took me a while to unravel.

Add info about doc source structure, etc

---

content/docs/0.13.x/operate/advanced_install_options/index.md
content/docs/0.13.x/operate/api_token/index.md

- provides docs for keptn/keptn#6312

docs: Add documentation for user-provided API token secret

---

config.toml
content/docs/news/release_announcements/keptn-0130/index.md
layouts/partials/announcement.html

Preview: https://deploy-preview-1055--keptn.netlify.app/

Announce Keptn 0.13.0

---

content/docs/quickstart/_index.md

Use Keptn 0.13.0 in Quick Start

---

content/docs/0.13.x/operate/user_management/microsoft/index.md
content/docs/0.13.x/operate/user_management/openid_authentication/index.md

closes https://github.com/keptn/keptn/issues/6086

doc: added documentation of CLI Oauth

---

content/docs/0.13.x/quality_gates/sli/index.md

Fixed broken link to Dynatrace SLI config

---

content/docs/news/_index.md

Referenced newsletter in https://keptn.sh/docs/news/

---

content/docs/concepts/secrets/index.md

https://github.com/keptn/keptn.github.io/issues/1003 
Move content from https://github.com/keptn/keptn/blob/master/statistics-service/README.md into Concepts section of documentation

Add documentation about Secret Service

---

content/docs/quickstart/_index.md

docs: Add info on how to access the bridge

---

content/docs/0.13.x/continuous_delivery/deployment_helm/index.md

Improved documentation for user_managed Helm Charts

---

content/docs/0.14.x/continuous_delivery/deployment_helm/index.md

Update Helm Chart deployment documentation

---

CONTRIBUTING.md

docs: Add doc for DCO

---

CODEOWNERS

Please remove me from the CODEOWNERS file

chore: remove Christian as a codeowner

---

CONTRIBUTING.md

* Add instructions to regularly sync fork with master
* Changed title to include "documentation" string

Add instructions to sync fork with master; change title

---

content/docs/quickstart/_index.md

Adds helm to main page and attempts to simplify flow for new users.

Make quickstart more readable and usable

---

content/docs/news/vulnerability_bulletins/keptn-sec-2022-001/index.md

docs: Announce Keptn Vulnerability 2022-001

---

content/docs/0.13.x/operate/backup_and_restore/index.md
content/docs/0.14.x/operate/backup_and_restore/index.md

The description of the bug can be found here: https://github.com/keptn/keptn/issues/7167
We should merge it, once we have the integration test in place. 

fix: Move reset-git-repos.sh into ./data/config

---

.github/workflows/ISSUE_TEMPLATE/config.yml
.github/workflows/ISSUE_TEMPLATE/document.md

Signed-off-by: Biki-das <bikid475@gmail.com>
this one is related to #1111 , i messed up the last pr with some accidental push , sorry for that 😅, here is the new one with the required changes.

Github:-Added issue template for doc and slack url

---

content/docs/news/vulnerability_bulletins/keptn-sec-2022-001/index.md

Announce release Keptn 0.12.6

---

content/docs/0.13.x/operate/install/index.md

This is a duplicate of https://github.com/keptn/keptn.github.io/pull/1122 to be merged into 0.14

add intro to install page for 0.14

---

content/docs/0.13.x/operate/install/index.md

Added a bit of contextual, intro text.

add intro to install page

---

CONTRIBUTING.md

Signed-off-by: Biki-das <bikid475@gmail.com>
Many new contributors especially beginners who start to contribute usually face a problem in keeping the local repo to be in sync with the main repo , a small explaining line might help to them to keep their development workflow seamless.

chore: Added a few lines on keeping in sync with the repo

---

content/docs/0.14.x/operate/backup_and_restore/index.md

Signed-off-by: Anwer Sayeed <deeyasrewna@gmail.com>

Fixed "backup" vs "back up" in Backup & Restore page in 0.14.x folder

---

.github/CODEOWNERS

Add @oleg-nenashev as a reviewer, remove Alois

---

.github/dependabot.yml

feat: Add Dependabot

---

content/docs/0.13.x/operate/install/index.md
content/docs/0.13.x/operate/k8s_support/index.md
content/docs/0.14.x/operate/install/index.md
content/docs/0.14.x/operate/k8s_support/index.md

Solves issue #1121. 
Signed-off by Subham Ghosh: subhamgcon@gmail.com

Adding K3d installation instructions.

---

content/docs/0.12.x/_index.md
content/docs/0.13.x/_index.md
content/docs/news/release_announcements/keptn-0124/index.md
content/docs/news/release_announcements/keptn-0126/index.md
content/docs/news/release_announcements/keptn-0133/index.md
content/docs/news/release_announcements/keptn-0134/index.md
content/docs/news/vulnerability_bulletins/keptn-sec-2022-001/index.md
content/docs/quickstart/_index.md
layouts/partials/announcement.html

Add missing releases

---

content/community/contributing/index.md

Improve contributing guide, reference mentorship programs

---

config.toml
content/docs/0.11.x/_index.md
content/docs/0.14.x/continuous_delivery/deployment_helm/index.md
content/docs/0.14.x/integrations/custom_integration/index.md
content/docs/0.14.x/operate/advanced_install_options/index.md
content/docs/0.14.x/operate/install/index.md
content/docs/0.14.x/operate/k8s_support/index.md
content/docs/0.14.x/operate/multi_cluster/index.md
content/docs/0.14.x/operate/upgrade/index.md
content/docs/news/release_announcements/keptn-0141/index.md
content/docs/quickstart/_index.md
layouts/partials/announcement.html

Do not merge yet
Preview: https://deploy-preview-1163--keptn.netlify.app/

Announce Keptn 0.14.x

---

content/docs/0.14.x/_index.md
content/docs/0.14.x/operate/upgrade/index.md
content/docs/news/release_announcements/keptn-0141/index.md

Add breaking change with integration and Keptn 0.14.x

---

content/docs/0.14.x/operate/install/index.md

h/t @agrimmer for his remarks in the #help channel

Add note about k8s for installation troubleshooting

---

content/docs/0.14.x/monitoring/dynatrace/install/index.md
content/docs/0.15.x/monitoring/dynatrace/install/index.md

Change DT URL to be aligned with official documentation

---

content/docs/0.15.x/operate/install/index.md

Apply https://github.com/keptn/keptn.github.io/pull/1171 to 0.15.x.

Add k8s troubleshooting note to 0.15.x (PR1171)

---

content/docs/0.13.x/operate/upgrade/index.md

Update upgrade doc to latest 0.13 version

---

content/docs/quickstart/_index.md

Per @agardnerIT -- kindkeptn v12 fixes some problems in kindkeptn v11 so update docs to use the new version.

Upgrade to kindkeptn 12

---

content/docs/news/release_announcements/keptn-0127/index.md

docs: Release announcement 0.12.7

---

content/docs/news/release_announcements/keptn-0135/index.md

Release announcement 0.13.5

---

content/docs/0.14.x/operate/advanced_install_options/index.md
content/docs/0.15.x/operate/advanced_install_options/index.md

Signed-off-by: odubajDT <ondrej.dubaj@dynatrace.com>
Resolves: https://github.com/keptn/keptn/issues/6811

docs: Introduce Write Concern options to MONGODB_EXTERNAL_CONNECTION_STRING

---

content/docs/0.14.x/quality_gates/get_started/index.md
content/docs/0.15.x/quality_gates/get_started/index.md

Changes applied to 0.14.x and  0.15.x

Fix xrefs in quality-gates

---

content/docs/0.14.x/operate/user_management/openid_authentication/index.md
content/docs/0.15.x/operate/user_management/openid_authentication/index.md

Changes applied to 0.14.x and 0.15.x

Fix xref to bridge/oauth; setup -> set up

---

content/docs/0.15.x/operate/k8s_support/index.md

* Update of K8s support matrix
* Removed suspect footnote

Update of Kubernetes support matrix

---

content/docs/0.14.x/operate/install/index.md
content/docs/0.16.x/manage/git_upstream/index.md
content/docs/0.16.x/operate/install/index.md

Cleaning up a few more broken xrefs. 
I just deleted the section about Quick Start from the Installation page.  We are reworking all of this and what is currently there doesn't really work.

Fix a few more xrefs

---

content/docs/news/release_announcements/keptn-0136/index.md
content/docs/news/release_announcements/keptn-0143/index.md
content/docs/news/release_announcements/keptn-0151/index.md

Add the release notes for the backport releases 0.13, 0.14, 0.15

---

content/docs/0.12.x/_index.md
content/docs/0.16.x/_index.md
content/docs/0.16.x/operate/advanced_install_options/index.md
content/docs/0.16.x/operate/install/index.md
content/docs/0.16.x/operate/uninstall/index.md
content/docs/0.16.x/operate/upgrade/index.md
content/docs/news/release_announcements/keptn-0160/index.md
layouts/partials/announcement.html

Announce Keptn 0.16.0

---

content/docs/0.16.x/operate/upgrade/index.md
content/docs/0.16.x/reference/files/shipyard/index.md
content/docs/news/release_announcements/keptn-0160/index.md

As we improved the CI build, we fixed a lot of issues,
sadly the branch was not fully up to date and some
issues are now failing the build

Fixing Post CI Improvement Errors

---

content/docs/0.16.x/api/git_provisioning/index.md
content/docs/0.16.x/operate/install/index.md

Fixes https://github.com/keptn/keptn/issues/8105
Fixes https://github.com/keptn/keptn/issues/8104

docs: Fix missing version flag and helm value for Git Provisioning

---

.htmltest.yml

Fixing urls linking to unreleased versions

---

content/docs/0.16.x/bridge/_index.md
content/docs/0.17.x/bridge/_index.md

Fix formatting in keptn-bridge "Uniform" section

---

content/docs/0.14.x/_index.md
content/docs/0.17.x/_index.md
content/docs/news/release_announcements/keptn-0161/index.md
content/docs/news/release_announcements/keptn-0170/index.md
layouts/partials/announcement.html

Announce Keptn 0.17 and 0.16.1

---

.htmltest.yml

Add Keptn slack to xrefs that are ignored

---

content/docs/0.17.x/reference/files/shipyard/index.md

This is based on a response @grabnerandi gave in the #help channel.

Can sequences be run in parallel?

---

content/docs/concepts/keptn-tools/index.md

@agardnerIT wrote up this delightful little piece that explains something we don't otherwise cover explicitly in our docs.  We do not currently have a really good place for it but I am including it in Concepts for now.
https://github.com/keptn/keptn.github.io/issues/1297

Add page about Keptn and other tools

---

content/docs/0.18.x/_index.md

Make 0.18.x appear above 0.17.x

---

content/docs/0.10.x/reference/cli/commands/keptn_configure_monitoring.md
content/docs/0.10.x/reference/cli/commands/keptn_create_project.md
content/docs/0.10.x/reference/cli/commands/keptn_delete_project.md
content/docs/0.10.x/reference/cli/commands/keptn_install.md
content/docs/0.10.x/reference/cli/commands/keptn_uninstall.md
content/docs/0.10.x/reference/cli/commands/keptn_update_project.md
content/docs/0.10.x/reference/cli/commands/keptn_upgrade.md
content/docs/0.10.x/reference/cli/commands/keptn_upgrade_project.md

Fix broken links where the release part is missing in the URL.

docs: Fix broken links

---

content/docs/0.18.x/integrations/webhooks/_index.md
content/docs/news/release_announcements/keptn-0180/index.md
layouts/partials/announcement.html

Signed-off-by: Giovanni Liva <giovanni.liva.91@gmail.com>

Announce 0.18

---

content/docs/news/release_announcements/keptn-0181/index.md
layouts/partials/announcement.html

docs: Announce 0.18.1

---

content/docs/0.18.x/_index.md

Publish 0.18.x docs

---

content/docs/0.18.x/manage/tasks/index.md

This captures information provided by @thisthat , @christian-kreuzberger-dtx , and @grabnerandi  in response to a customer question in Slack (https://keptn.slack.com/archives/CNRCGFU3U/p1657713622781609 ).

How to stop an executing task

---

content/docs/0.18.x/manage/tasks/index.md

This PR adds a new section about how to identify and stop a stalling sequence that is preventing other sequences from being executed.

How to identify and stop a blocking sequence

---

content/home/usage.md

Adds the "Keptn In A Nutshell" video to the homepage.

Homepage: Add keptn overview video

---

content/docs/0.18.x/reference/files/shipyard/index.md

Clarify Task wording

---

content/docs/install/cli-install/index.md

Add homebrew instructions + fix old link

---

.github/CODEOWNERS

Add @StackScribe as an owner / maintainer of this repo.

add @StackScribe as maintainer

---

layouts/partials/contact.html

fixes #1328 
Signed-off-by: Omkar kulkarni [88308267+Omkar0114@users.noreply.github.com](mailto:88308267+Omkar0114@users.noreply.github.com)

changed status `Sandbox` to `Incubating`

---

content/docs/0.18.x/bridge/_index.md

- Removed broken link for manual approval strategy
- Fixes some typos
>
Signed-off-by: TannerGilbert <gilberttanner.work@gmail.com

chore: Removed broken link for manual approval strategy

---

content/docs/install/_index.md
content/docs/install/cli-install/index.md

https://github.com/keptn/keptn.github.io/issues/1332

Clarify Keptn CLI installation

---

content/docs/0.19.x/manage/plan/index.md

Adam and Andi, I need a quick read and your honest opinions.  I had the idea of someone new to Keptn.  They've been through the introductory material and now are ready to create their first project, possibly for production.  It seemed that we needed a little document that supports them as they plan their first project.
So I scratched this out.  At the very best, it needs more topics and more depth -- maybe info about pros and cons of different approaches or alternate ways of accomplishing a task.  But it may be that this is the sort of piece that writers think are cool and nobody else ever reads.  I keep going back and forth so need other opinions before I do more work.  It may be that these considerations and options should be …

Planning your project

---

content/docs/news/release_announcements/keptn-0162/index.md
content/docs/news/release_announcements/keptn-0171/index.md
content/docs/news/release_announcements/keptn-0182/index.md
layouts/partials/announcement.html

Announce backports for 0.16-18

---

content/docs/0.19.x/operate/backup_and_restore/index.md

Signed-off-by: odubajDT <ondrej.dubaj@dynatrace.com>
https://github.com/keptn/keptn/issues/8781

Modify backup and restore commands also considering Resource Service

---

content/docs/integrations/_index.md

This PR:
- Resolves and fixes #1419 

fix:Add missing categories

---

content/docs/quickstart/_index.md

Small PR to add missing link to helm.sh

Add missing helm link to Quickstart page

---

content/docs/0.19.x/define/triggers/index.md

link to Adam's "Trigger a sequence" video from "Triggers" page

---

content/docs/0.19.x/_index.md
content/docs/news/release_announcements/keptn-0190/index.md
layouts/partials/announcement.html

DO NOT MERGE IT YET
Build fails due to the IETF website being slow: https://tools.ietf.org/html/rfc7636

Announce 0.19.0

---

content/docs/0.19.x/_index.md
content/docs/0.19.x/define/_index.md
content/docs/0.19.x/define/simple-project/index.md
content/docs/0.19.x/reference/files/shipyard/index.md

0.19.x not future; fix broken xrefs in define section

---

content/docs/0.19.x/define/_index.md
content/docs/0.19.x/define/infracost/index.md

This PR creates a page that just presents a video demonstration, with a brief introduction that describes what is in that intro.
In addition to evaluating the actual material, please evaluate the presentation method.  This may be a way to utilize videos we have to improve the contents of this section.

Add page to "define" section with Adam's infracost example

---

content/docs/0.19.x/define/_index.md
content/docs/0.19.x/define/delivery_sequence/index.md
content/docs/0.19.x/define/quality-gates/index.md

This PR:
* Adds a link to Adam's video about implementing a quality gate evaluation, with a brief description. 
* Adds a mention of this video to the listing on the landing page for "Define a project"
* Corrects the weight of the delivery_sequence page so the sections are listed in the same order used for the descriptive list.

Add link to Adam's video with brief description

---

content/docs/integrations/_index.md

Add finops and security filters

---

content/docs/integrations/_index.md

- Adds detail text for each integration
- Adds message if no integration with a specific feature or search term could be found
Resolves #1439
The check if no integrations are available could possibly fail if the call takes longer than the timeout specified in content/docs/integrations/_index.md#66.
Signed-off-by: TannerGilbert <gilberttanner.work@gmail.com>

feat: Improve text for integrations

---

content/docs/0.19.x/define/_index.md
content/docs/0.19.x/define/infracost/index.md
content/docs/0.19.x/define/security/index.md

This PR provides a bit of information about using Keptn to identify security vulnerabilities.
https://github.com/keptn/keptn.github.io/issues/1441

Using Keptn to identify security vulnerabilities

---

content/docs/0.19.x/reference/miscellaneous/distributor/index.md
content/docs/concepts/architecture/index.md

This PR:
*  captures information @bacherfl and @agardnerIT  provided to a customer about how NATS actually works in Keptn
* captures an answer that @mowies provided to a customer while I had this branch open so I stuck it in
* Fixes a couple xrefs that slid through the cracks
https://github.com/keptn/keptn.github.io/issues/1436

More architectural info for NATS, mongodb

---

CONTRIBUTING.md
layouts/partials/sidebar-multicard.html
layouts/shortcodes/popup_image.html
makefile
netlify.toml

Upgrading to a more recent version of hugo.
The page is building, and looks good, but there might be hidden regressions which somebody working with the documentation should actually inspect

Upgrading hugo to 0.105

---

content/docs/1.0.x/install/upgrade/index.md

This PR updates the "Update" section for 1.0.x.
Fixes #1501

Update the "Update" page for 1.0.x-LTS

---

content/docs/0.19.x/api/git_provisioning/index.md
content/docs/0.19.x/define/deployment_helm/index.md
content/docs/0.19.x/integrations/custom_integration/index.md
content/docs/install/helm-install/index.md
content/docs/install/multi-cluster/index.md

ONLY GIOVANNI SHOULD MERGE THIS PR.
This PR updates the 0.19.x documentation to use 0.19.2 in example commands and files.  Giovanni will merge it when he merges the 0.19.2 release.

Update to 0.19.2 in sample commands and files

---

content/docs/1.0.x/integrations/action_provider/index.md
content/docs/1.0.x/integrations/custom_integration/index.md
content/docs/1.0.x/integrations/how_integrate/index.md
content/docs/1.0.x/integrations/sli_provider/index.md
content/docs/1.0.x/integrations/webhooks/_index.md
content/docs/1.0.x/integrations/webhooks/examples/index.md
content/docs/1.0.x/integrations/webhooks/jenkins/index.md

This PR updates the files in the integrations section to use 1.0.0 -- mostly for the keyword metadata except for one file.
Part of https://github.com/keptn/keptn.github.io/issues/1511

update custom integration pages to 1.0.0

---

content/docs/0.19.x/api/git_provisioning/index.md
content/docs/0.19.x/define/deployment_helm/index.md
content/docs/0.19.x/integrations/custom_integration/index.md
content/docs/install/helm-install/index.md
content/docs/install/multi-cluster/index.md

GIOVANNI WILL MERGE THIS PR WHEN THE TIME IS RIGHT.  NO ONE ELSE SHOULD MERGE.
This updates all "0.19.2" strings in sample commands and files to be "0.19.3"

Update command and file examples to 0.19.3

---

content/docs/news/release_announcements/keptn-0193/index.md

Thanks to @Giulia-dipietro for noticing it

Fix Release name

---

README.md
layouts/_default/baseof.html
layouts/partials/scarf.html

First iteration of adding a scarf pixel to the page. In the next iteration we can think of seperating, or providing differnt pixels for different sections, to have a better overview over traffic.

Adding Scarf-Pixel to Page

---

content/docs/install/k8s-support/index.md

docs: Add scaling guidelines

---

content/docs/install/helm-install/index.md

Fixes https://github.com/keptn/keptn/issues/8521

Fix missign redirect

---

content/docs/1.0.x/concepts/architecture/index.md
content/docs/1.0.x/concepts/delivery/index.md
content/docs/1.0.x/concepts/performance_validation/index.md
content/docs/1.0.x/concepts/quality_gates/index.md
content/docs/1.0.x/reference/files/action-provider/index.md
content/docs/concepts/delivery/index.md
content/docs/tutorials/_index.md

Little fixes found while reading through docs I haven't read for a while.

Miscellaneous little fixes

---

content/docs/0.16.x/_index.md
content/docs/0.17.x/_index.md
content/docs/0.18.x/_index.md
content/docs/0.19.x/_index.md
content/docs/1.0.x/_index.md
content/docs/news/release_announcements/keptn-100/index.md
layouts/partials/announcement.html

Announce 1.0.0

---

content/docs/_index.md
content/why-keptn/_index.md
layouts/partials/announcement.html
layouts/partials/main-menu-mobile.html
layouts/partials/main-menu.html

Preview: https://deploy-preview-1549--keptn.netlify.app/

Add link to KLT in the menu

---

content/docs/install/helm-install/index.md

Signed-off-by: Shardul Srivastava <shardul.srivastava007@gmail.com>
This PR fixes https://github.com/keptn/keptn/issues/9325 and fixes the instructions related to Helm installation.

docs: fix helm installation instructions

---

content/docs/1.0.x/install/helm-install/index.md

This PR captures small changes to the helm-install page that were suggested in an unrelated PR.

Ingress Controller -> ingress controller

---

CONTRIBUTING.md

Add note about SEO and xrefs to CONTRIBUTING.md

---

content/community/newsletter/index.md

Signed-off-by: David Hirsch <david.hirsch@dynatrace.com>

Added signup link to newsletter

---

content/docs/1.0.x/install/helm-install/index.md

Signed-off-by: Diego Braga <diego.braga86@gmail.com>

docs: fix jsonpath command to retrieve credentials

---

content/docs/1.0.x/manage/plan/index.md

This captures information @grabnerandi provided in response to a user question in https://keptn.slack.com/archives/CNRCGFU3U/p1673419042795069 .

Add info to "planning" about options for deploying tools for a project

---

layouts/sitemap.xml

If we do not find a proper date for a page, we assume the build date.

Fix sitemap last modified date

---

content/docs/news/release_announcements/keptn-110/index.md
layouts/partials/announcement.html

Add release notes for Keptn 1.1.0

---

content/docs/1.0.x/_index.md

Show Keptn 1.y.z LTS in the left frame for the V1 docs

Rename release 1.y.z

---

content/docs/1.0.x/install/troubleshooting/index.md

https://github.com/keptn/keptn.github.io/issues/1581

Use keptn-mongo in command to correct permissions on OpenShift

---

content/docs/1.0.x/reference/files/slo/index.md

Signed-off-by: Amishakumari544 <amishakumari544@gmail.com>
This PR fixes #1528

Adding SLO spec link to SLO reference page

---

content/docs/1.0.x/reference/files/sli/index.md
content/docs/1.0.x/reference/files/slo/index.md

Adding Sli spec link 

---

config.toml
layouts/partials/canonical.html
layouts/robots.txt

Adding robots.txt to point to the sitemap
Improving canonical links for root doc pages, if there is the same page within the current-versions

Further SEO Improvements

---

content/docs/1.0.x/install/k8s/index.md

fixed formatting errors in install/k8

---

config.toml
content/docs/news/release_announcements/keptn-120/index.md
layouts/partials/announcement.html

Release 1.2.0

---

README.md

This PR:
- Adds dynamic contrib.rocks code as described in https://github.com/keptn/community/issues/221

Add contrib.rocks code

---

content/docs/1.0.x/install/access/index.md

fixed spelling error

---

content/docs/install/access/index.md
content/docs/install/k8s/index.md

- fixes some indentation issues in code blocks that resulted in code block rendering issues
- replaces some `console` code block annotations with `shell` code block annotations
Fixes #1619

docs: fix indents and code block language tags

---

content/docs/1.0.x/install/access/index.md

Also made a couple trivial edits.

Fix formatting in "Access options"

---

config.toml
content/docs/0.10.x/manage/git_upstream/index.md
content/docs/0.11.x/manage/git_upstream/index.md
content/docs/0.12.x/manage/git_upstream/index.md
content/docs/0.13.x/manage/git_upstream/index.md
content/docs/0.17.x/manage/git_upstream/index.md
content/docs/0.19.x/manage/git_upstream/index.md
content/docs/0.5.0/manage/project/index.md
content/docs/0.6.0/manage/project/index.md
content/docs/0.7.x/manage/git_upstream/index.md
content/docs/0.8.x/manage/git_upstream/index.md
content/docs/0.9.x/manage/git_upstream/index.md
content/docs/1.0.x/manage/git_upstream/index.md
content/docs/news/release_announcements/keptn-130/index.md
layouts/partials/announcement.html

chore: release Keptn v1.3.0

---

content/home/headline.md
layouts/partials/intro.html

added button for better visibility
adding some nice buttons to the start page to help people for better navigation

feat: adding better visibility for klt

---

content/community/_index.md
content/community/contributing/index.md

change from #advocacy-and-outreach to #community-and-outreach

docs: update slack link
